### ISSUE TITLE
Enable Dependabot

### ISSUE THREAD

**Issue by dannasessha** [zingolabs/zingo-mobile#13]
https://github.com/zecwalletco/zecwallet-mobile has new changes from dependabot we should review and (probably) merge in.

**Comment by zancas** [comment]
Thanks for making this issue.

**Comment by dannasessha** [comment]
After some discussion it's been loosely decided to add our own dependabot integration, using a configuration checked into our repo. I've begun work on this, which will be seen (pre-PR) over [on a branch](https://github.com/dannasessha/zecwallet-mobile/tree/dependabot_init) based off my own fork of the project.

**Comment by zancas** [comment]
Here's a screenshot of the recent dependabot updates on upstream.  I'm depending on this issue to keep track of this, and ensure that we update as well.
![dependa_bumps](https://user-images.githubusercontent.com/640955/170105996-0c8ef24d-f163-4777-8481-8d2d3f5965fc.png)

**Comment by zancas** [comment]
dependabot appears to be enabled and to have reasonable tracking mechanisms built-in.
