### ISSUE TITLE
Consider Yarn version update

### ISSUE THREAD

**Issue by dannasessha** [zingolabs/zingo-mobile#15]
Our `yarn` version appears to be `v1`. `Yarn v2` [came out in early 2020](https://dev.to/arcanis/introducing-yarn-2-4eh1). There seem to be significant obstacles to updating, but it is perhaps worth consideration or tracking this issue.

`v2` changes the way that packages are handled and thus interfaces to thinks like `react` might also be disrupted. Also, dependabot does not support `v2` - though it seems like they may try to support `v3` skipping `v2`.

**Comment by dannasessha** [comment]
`v2`  offers an option that copies packages to the node_modules/ folder just like `v1`, providing backward compatibility for these projects. It requires adding a single line to your new .yarnrc.yml configuration file.

Also, https://yarnpkg.com/getting-started/migration

**Comment by dannasessha** [comment]
https://yarnpkg.com/getting-started/qa/#why-should-you-upgrade-to-yarn-modern

**Comment by zancas** [comment]
Please pull a branch (and `git worktree`, and `zellij` tab-or-session) for this and begin hacking.   This is not high-priority but we do need someone to start work on it.

**Comment by juanky201271** [comment]
@dannasessha What do you think about this Issue????

**Comment by zancas** [comment]
I am not qualified to comment on the differences between yarn versions, but, if you two decide to dig into the topic, I vote that we first attempt to upgrade:

https://github.com/zingolabs/zingo-pc

**Comment by juanky201271** [comment]
> I am not qualified to comment on the differences between yarn versions, but, if you two decide to dig into the topic, I vote that we first attempt to upgrade:
> 
> https://github.com/zingolabs/zingo

Did you mean: `zingo` or `zingo-mobile`??????

**Comment by juanky201271** [comment]
I think for a React Native project to change to Yarn v2 or even v3 have less sense than for other React projects. I think the React Native Team did not too much about the new PnP tech that Yarn v2-3..... I think It's a good idea to work on the project that @zancas said.

**Comment by juanky201271** [comment]
Maybe it's a good idea to transfer this issue to `zingo-pc`, if exists the intention to upgrade yarn... honestly I don't know it is worthy.

**Comment by zancas** [comment]
OK, I updated my comment to point to the new name of the project.   I still think it makes sense to test against that project first if we're considering upgrading.   If I Understand Correctly, there's not yet a compelling reason to upgrade.
