### ISSUE TITLE
bad-orchard-bundle-authentication

### ISSUE THREAD

**Issue by AloeareV** [zingolabs/zingo-mobile#195]
Attempts to send are sporadically causing a `bad-orchard-bundle-authentication` response from lightwalletd/zcashd. It doesn't seem to be unique to zingo-mobile, so it's likely an issue with an underlying dependency. We're working on root-causing this. https://github.com/zcash/zcash/issues/6440

**Comment by juanky201271** [comment]
I have three videos of this problem, maybe those can added some value to resolve this issue...

https://user-images.githubusercontent.com/43755989/219891672-9cd9afb2-b331-4b70-9f71-6091293b678d.mp4

**Comment by juanky201271** [comment]
https://user-images.githubusercontent.com/43755989/219891686-cdd1aee4-0db0-4096-a379-5dc1cbbca04f.mp4

**Comment by juanky201271** [comment]
https://user-images.githubusercontent.com/43755989/219891698-bf30b83c-5e67-4346-9257-e06b4bcbf2f4.mp4

**Comment by juanky201271** [comment]
I think this is relevant for this issue: https://github.com/zcash/orchard/pull/385

**Comment by juanky201271** [comment]
We fixed this problem in the new version... closing.
