### ISSUE TITLE
Error sending: error_code: -25, error_message: "Missing inputs" 

### ISSUE THREAD

**Issue by juanky201271** [zingolabs/zingo-mobile#206]
I started to get this error, while sending... `SendResponse { error_code: -25, error_message: "Missing inputs" }` Do you know what is this?
Example:
`[{"address": "UA adress", "amount": 2000, "memo": "Yuju"}]`

**Comment by juanky201271** [comment]
The first error was this: ` SendResponse { error_code: -26, error_message: "18: bad-txns-orchard-duplicate-nullifier" }` and after that I got the `missing inputs` error all the time.
My wallet is not fully synced.

**Comment by juanky201271** [comment]
I can't reproduce again,,,

**Comment by zancas** [comment]
I think what's happening is that:
  1 the wallet is not fully synced
      * it detects notes that it doesn't _realize_ it has spent in the future
      * it tries to spend them, but the validator tells the wallet that the nullifiers have already been used
      * after that it removes the used nullifiers, but now it does not have "inputs" (new previously unpublished, nullifiers to replace them with)
