### ISSUE TITLE
Landscape mode has display bugs

### ISSUE THREAD

**Issue by zancas** [zingolabs/zingo-mobile#209]
![landscape_glitch](https://user-images.githubusercontent.com/640955/220730848-c85739e3-7ec7-400a-946d-09a6e1d7afd6.jpeg)

![landscape_glitch2](https://user-images.githubusercontent.com/640955/220731447-84408b19-9f44-49a9-bcea-c7df2957b21a.png)

**Comment by juanky201271** [comment]
If something have a little bug then the policy is: `remove it right away`... so we can end up with a empty repo... 
The landscape mode was a fair amount of work, but who cares.
Tell me if there are more code to remove... because it feels good.
