### ISSUE TITLE
zingolib command: `sendprogress` - Info

### ISSUE THREAD

**Issue by juanky201271** [zingolabs/zingo-mobile#214]
I need to know everything about the data from this command. Because in all my tests this info are totally chaotic and It's impossible to give a good UX to the user...

**Comment by zancas** [comment]
Hi!  Is this request still active?

Here's a dump from `zingo-cli --regtest` for starters:

```
(regtest) Block:1 (type 'help') >> sendprogress
{
  "id": 0,
  "sending": false,
  "progress": 0,
  "total": 0,
  "txid": null,
  "error": null,
  "sync_interrupt": false
}
(regtest) Block:1 (type 'help') >>
```

**Comment by juanky201271** [comment]
@zancas Well, I know how is the JSON from this command, and I already use it in zingo-mobile.

I wish to know how these fields (`progress` & `total`) change along the `send` process, because those values are totally random...

I expect something like this (this is an example):
* progress = 0 / total = N
* progress = 1 / total = N
* progress = 2 / total = N
* ...
* ...
* progress = N - 2 / total = N
* progress = N - 1 / total = N
* progress = N / total = N

But the reality is really different.

**Comment by zancas** [comment]
OK, I will investigate their definitions.

Based on [this line of code](https://github.com/zingolabs/zingolib/blob/3312c5053c517d50fca0beb5524e6ac948c3d4e2/zingolib/src/wallet.rs#L1452) it looks like progress is a time..  probably in units of seconds?   Is it non-decreasing?

**Comment by zancas** [comment]
[This line of code](https://github.com/zingolabs/zingolib/blob/3312c5053c517d50fca0beb5524e6ac948c3d4e2/zingolib/src/wallet.rs#L1463) hints to me that the `send_progress.total` is the number of sapling outputs for a particular..  hmm transaction.

**Comment by zancas** [comment]
I need to check this more carefully, and if correct add doc-comments to [SendProgress](https://github.com/zingolabs/zingolib/blob/3312c5053c517d50fca0beb5524e6ac948c3d4e2/zingolib/src/wallet.rs#L77).  Do those interpretations make sense with your observations?

**Comment by juanky201271** [comment]
What are you saying can make sense with I can remember...

This is an old log that I saved:

 LOG  prev progress {"error": null, "id": 2, "progress": 3, "sending": false, "total": 1, "txid": "dd51d4484de3af8d255ed835ea2498f70ec99961d4f661579f3df4a5eeb65d54"}
 LOG  progress {"error": null, "id": 3, "progress": 0, "sending": true, "total": 1, "txid": null}
 LOG  Seconds Per compute = 3
 LOG  ETA = 12
 LOG  ETA calculated = 12
 LOG  progress {"error": null, "id": 3, "progress": 0, "sending": true, "total": 1, "txid": null}
 LOG  Seconds Per compute = 3
 LOG  ETA = 12
 LOG  ETA calculated = 12
 LOG  progress {"error": null, "id": 3, "progress": 0, "sending": true, "total": 1, "txid": null}
 LOG  Seconds Per compute = 3
 LOG  ETA = 12
 LOG  ETA calculated = 12
 LOG  progress {"error": null, "id": 3, "progress": 0, "sending": true, "total": 1, "txid": null}
 LOG  Seconds Per compute = 3
 LOG  ETA = 12
 LOG  ETA calculated = 12
 LOG  progress {"error": null, "id": 3, "progress": 0, "sending": true, "total": 1, "txid": null}
 LOG  Seconds Per compute = 3
 LOG  ETA = 12
 LOG  ETA calculated = 12
 LOG  progress {"error": null, "id": 3, "progress": 0, "sending": true, "total": 1, "txid": null}
 LOG  Seconds Per compute = 3
 LOG  ETA = 12
 LOG  ETA calculated = 12
 LOG  progress {"error": null, "id": 3, "progress": 0, "sending": true, "total": 1, "txid": null}
 LOG  Seconds Per compute = 3
 LOG  ETA = 12
 LOG  ETA calculated = 12
 LOG  progress {"error": null, "id": 3, "progress": 0, "sending": true, "total": 1, "txid": null}
 LOG  Seconds Per compute = 3
 LOG  ETA = 12
 LOG  ETA calculated = 12
 LOG  progress {"error": null, "id": 3, "progress": 1, "sending": true, "total": 1, "txid": null}
 LOG  Seconds Per compute = 18.110000133514404
 LOG  ETA = 54
 LOG  ETA calculated = 54
 LOG  progress {"error": null, "id": 3, "progress": 2, "sending": true, "total": 1, "txid": null}
 LOG  Seconds Per compute = 10.18500006198883
 LOG  ETA = 20
 LOG  ETA calculated = 20
 LOG  progress {"error": null, "id": 3, "progress": 3, "sending": true, "total": 1, "txid": null}
 LOG  Seconds Per compute = 7.78766671816508
 LOG  ETA = 8
 LOG  ETA calculated = 8
 LOG  progress {"error": null, "id": 3, "progress": 3, "sending": true, "total": 1, "txid": null}
 LOG  Seconds Per compute = 8.426666736602783
 LOG  ETA = 8
 LOG  ETA calculated = 8
 LOG  progress {"error": null, "id": 3, "progress": 3, "sending": true, "total": 1, "txid": null}
 LOG  Seconds Per compute = 9.05300005276998
 LOG  ETA = 9
 LOG  ETA calculated = 9
 LOG  progress {"error": null, "id": 3, "progress": 3, "sending": true, "total": 1, "txid": null}
 LOG  Seconds Per compute = 9.73966670036316
 LOG  ETA = 10
 LOG  ETA calculated = 10
 LOG  progress {"error": null, "id": 3, "progress": 3, "sending": true, "total": 1, "txid": null}
 LOG  Seconds Per compute = 10.491333405176798
 LOG  ETA = 10
 LOG  ETA calculated = 10
 LOG  progress {"error": null, "id": 3, "progress": 3, "sending": true, "total": 1, "txid": null}
 LOG  Seconds Per compute = 10.91866668065389
 LOG  ETA = 11
 LOG  ETA calculated = 11
 LOG  progress {"error": null, "id": 3, "progress": 3, "sending": true, "total": 1, "txid": null}
 LOG  Seconds Per compute = 12.126000006993612
 LOG  ETA = 12
 LOG  ETA calculated = 12
 LOG  progress {"error": null, "id": 3, "progress": 3, "sending": true, "total": 1, "txid": null}
 LOG  Seconds Per compute = 12.339333375295004
 LOG  ETA = 12
 LOG  ETA calculated = 12
 LOG  End Send OK: {
  "txid": "4aa240c53676b17b36dbd4c76d303e2ed4cf9b7086281003b71aafa387534f90"
}
 LOG  progress {"error": null, "id": 3, "progress": 3, "sending": false, "total": 1, "txid": "4aa240c53676b17b36dbd4c76d303e2ed4cf9b7086281003b71aafa387534f90"}
 LOG  Seconds Per compute = 13.191000064214071
 LOG  ETA = 13
 LOG  ETA calculated = 13

**Comment by zancas** [comment]
> OK, I will investigate their definitions.
> 
> Based on [this line of code](https://github.com/zingolabs/zingolib/blob/3312c5053c517d50fca0beb5524e6ac948c3d4e2/zingolib/src/wallet.rs#L1452) it looks like progress is a time.. probably in units of seconds? Is it non-decreasing?

Well, this guess seems to have been wrong.  I think there are multiple things named "progress".   I believe the "progress" field of a `SendProgress` may be reporting the number of succesful steps in a a transaction build.

This is based on my current understanding of the definition of `r`...  I am still experimenting.

**Comment by juanky201271** [comment]
@zancas Sorry but I don't understand 100%.

sendprogress.progress: successful steps in a transaction build. right?
sendprogress.total: number of sapling outputs for a particular.. hmm transaction. right?

From my perspective these two fields are useless to show in the UI.

In my logs I can see:
* total with 1 all the time. (number of sapling outputs?????)
* progress changing from 0 to 3. (successful steps.... building tx??????)

For now this output is insufficient to create a useful feedback for the user while is waiting for the send process is over.

**Comment by juanky201271** [comment]
@zancas if with `progress` (successful step in a tx build) I could have the total of steps in a tx build, with those two fields I can do some UI-UX better...

Example:
- total-steps: 3
- progress: from 0 to 3.

**Comment by zancas** [comment]
OK, maybe we can do this, but I think it might often be too short for the user to care.

**Comment by juanky201271** [comment]
I'm glad you think that, but we have to give something to the user, I'm thinking in really slow internet connections... for instance. This process for me & you is almost instantaneous, for other users it can take maybe 10 or 20 seconds...

If this change is hard to do or risky, at least tell me what number we can assume for  `total-steps`. Now I'm using the hard-coded value: 4 phases/steps... and seems to fit in almost every tx building...

**Comment by zancas** [comment]
Hmm...   I don't _think_ the steps in the transaction construction are network dependent (though maybe the could be if the builder needs commitment data?).
I assumed that within-tx-construction steps are internal to the local state of the device.

**Comment by juanky201271** [comment]
AFAIK... Here we have two process:

- `send` -> which run in the server, I believe network dependent... (the tx build happen here)
- `sendprogress` -> which you can run meanwhile the process above is running... (this is a feedback of `send` with the number of the steps in a tx build...)

I don't know if we are in the same page, or maybe I'm loosing the point....

**Comment by juanky201271** [comment]
> @zancas if with `progress` (successful step in a tx build) I could have the total of steps in a tx build, with those two fields I can do some UI-UX better...
> 
> Example:
> 
>     * total-steps: 3
> 
>     * progress: from 0 to 3.

Here I was talking about the `sendprogress` process... maybe this is helpful to go somewhere with this issue...

**Comment by juanky201271** [comment]
Well, I think this issue is over, for now. Closing.
