### ISSUE TITLE
artwork

### ISSUE THREAD

**Issue by alfabetogreco** [zingolabs/zingo-mobile#222]
I thought i saw in a chat maybe you would want more different art options?  not sure what you want but maybe i can do some? i saw some GIMP files.

I started just to make sketches to start talking if you wanted https://github.com/alfabetogreco/zingart/tree/first_sketches

it would be nice to have leaf be on trees in the orchard forest but in a logo it is hard (too many things) but i could try, had a few ideas for images but maybe not a logo

tell me what you want or if you want me to keep trying anything!

**Comment by alfabetogreco** [comment]
these are only sketches of course to just try get conversation, ideas started

**Comment by zancas** [comment]
Interesting!  I will make sure people notice.

**Comment by juanky201271** [comment]
We are working in a new design, and I think the logo is OK for now. Thanks so much for taking the time to do this, we really appreciate it. Closing...
