### ISSUE TITLE
Better UI for better UX when Reconnect account.

### ISSUE THREAD

**Issue by Edicksonjga** [zingolabs/zingo-mobile#234]
When the user's device does not have enough memory (RAM/ROM) or is not connected to the internet, the wallet does not open the account and displays a window where the user needs to tap on "Open active wallet".

![Screenshot_20230306-134312.jpg](https://user-images.githubusercontent.com/37910384/223219411-a64fc35a-f958-412b-85fc-e3cbd798c476.jpg)

**First problem:**

This window can represent a serious UX issue as it is very similar to the Start window for the first time.

Tapping on Open active wallet sometimes doesn't work and shows the following error:
![Screenshot_20230306-161031.jpg](https://user-images.githubusercontent.com/37910384/223221898-9553bdf8-aebc-4975-bdae-10c73f6ded44.jpg)

_The user cries and cries because he thinks he lost his account and must start from scratch._

The window also offers options that a new user can touch and if you didn't save the seed, you lose the old account.

**Second problem:**

After the active wallet reconnection window is displayed:

1. Touch Restore
2. Return to the previous window
3. The "Open active wallet" option disappears

If at that precise moment the device connects to the internet or frees up memory, Zingo works again, but the user only sees two options:

- Create a new account.
- Restore account.

If you create a new account and didn't save the seed from the old account (think like a new user in Crypto), the account is lost.

If you tap on Restore, because if you saved the seed, the user has to start the synchronization again which is not good knowing how is the synchronization in Zcash.

https://user-images.githubusercontent.com/37910384/223221354-88665af4-ba26-480b-8f25-b70e03c0a01c.mp4

All this because the wallet shows you a window that should never have existed.

I hope they can fix it soon and come up with a better way to inform the user that their account is still active, but due to an error it cannot be opened at that moment. 😎👍

**Comment by juanky201271** [comment]
Thanks @Edicksonjga for this information. I just fix the issue when you come back from the `restore` screen. We will work in a new screen for this specific use case... I agree, the user only should see this screen the first time. If the App cannot open the current wallet then It should have another screen with a really good UX. This situation is really scary for everyone.

**Comment by Edicksonjga** [comment]
> Thanks @Edicksonjga for this information. I just fix the issue when you come back from the `restore` screen...

You are welcome! 👍

Yes, they have to do something to lessen the chance of users losing their wallets by mistake from a bug. 😁

I will be attentive to the changes and if you need me to do tests, you know where to contact me.

**Comment by juanky201271** [comment]
@Edicksonjga can you re-evaluate this issue with the new perspective of `basic` or `expert` mode? Thanks.

**Comment by Edicksonjga** [comment]
I'll be reviewing this soon, although I already reported a similar error in these Basic Mode screens/windows #441

You are welcome! @juanky201271

**Comment by Edicksonjga** [comment]
![Screenshot_20230717-065600.jpg](https://github.com/zingolabs/zingo-mobile/assets/37910384/811365fa-4c85-4d67-bf34-f86a5fa16ffe)

The screen is fine when you don't have internet, I like the integration of the tooltips, it would improve the texts a bit since the message is repetitive in the three visible texts (Connection status, second text, tooltips).

I will try to reproduce the case where it fails by cache. @juanky201271

**Comment by juanky201271** [comment]
I'm waiting for the new design, and I'm sure you are going to keep in mind this issue... @Edicksonjga

**Comment by juanky201271** [comment]
Well, I'm all ears, tell me about the texts you like & I will change them right away... Thanks @Edicksonjga

**Comment by juanky201271** [comment]
Any new about this? @Edicksonjga
