### ISSUE TITLE
scanner overlaps other components

### ISSUE THREAD

**Issue by fluidvanadium** [zingolabs/zingo-mobile#237]
![Screenshot_20230307-042340](https://user-images.githubusercontent.com/111296437/223320464-a279c18e-0de2-489c-b3f0-a4aab64673b5.png)

worse than this on some systems

**Comment by fluidvanadium** [comment]
@juanky201271 this was the bug that was causing me trouble with the tests today

**Comment by juanky201271** [comment]
@fluidvanadium 
The title is missing (something more?)... this screenshot is from your device or from some emulator... give me, please more info to reproduce it in my local env.... Thanks in advance.

**Comment by fluidvanadium** [comment]
> @fluidvanadium The title is missing (something more?)... this screenshot is from your device or from some emulator... give me, please more info to reproduce it in my local env.... Thanks in advance.

that first screenshot is from my phone.

here's a screenshot from a pixel 6 x86_64 emulator

![Screenshot from 2023-03-09 00-31-09](https://user-images.githubusercontent.com/111296437/223884433-ba0c51bf-3e33-437e-a9c1-02b1df415000.png)

I'm working on this now.

**Comment by juanky201271** [comment]
how is it going?

**Comment by juanky201271** [comment]
This is fixed already, thanks @fluidvanadium
