### ISSUE TITLE
memo confirm runs offscreen

### ISSUE THREAD

**Issue by fluidvanadium** [zingolabs/zingo-mobile#244]
![Screenshot from 2023-03-17 17-53-19](https://user-images.githubusercontent.com/111296437/225981566-6e32ab48-6e1c-46e5-9ea9-813f3800e341.png)

**Comment by juanky201271** [comment]
In this case maybe it is a good idea to remove the line for checking if the memo field `toBeVisible`... because in some screens can be off screen. Also I think the important thing here is that the memo field in the confirm screen was correct or not.

**Comment by fluidvanadium** [comment]
the second and third lines of the memo are not visible. maybe we need a scroll view?

**Comment by juanky201271** [comment]
> the second and third lines of the memo are not visible. maybe we need a scroll view?

https://github.com/zingolabs/zingo-mobile/blob/a269308e4da9d5e7de87f4fd7a594030b774b97b/components/Send/components/Confirm.tsx#L46

I think this screen have a Scroll View already. 
Another thing is to do the scrolling inside the e2e test...
