### ISSUE TITLE
Sync Report screen with wrong data when come back from the background

### ISSUE THREAD

**Issue by juanky201271** [zingolabs/zingo-mobile#254]
Wrong number of blocks synced.

5 batches -> 296 blocks (have to be from 500 to 599 blocks)

![Screenshot_2023-03-15-07-48-32-24](https://user-images.githubusercontent.com/43755989/226494838-dcbf6364-21cc-4e06-9ac6-c09f9349c65c.jpg)

**Comment by juanky201271** [comment]
Wrong number of blocks synced.

2 batches -> 50 blocks (have to be from 200 to 299 blocks)

![Screenshot_2023-03-19-16-44-09-03](https://user-images.githubusercontent.com/43755989/226495085-8cf89b50-c5a7-4216-80c8-a0ab4084c259.jpg)

**Comment by juanky201271** [comment]
@Oscar-Pepper Can you explain a little bit how were the circumstances for this issue... Thanks.

**Comment by Oscar-Pepper** [comment]
i wish i had more details but this was what happened:
1. i opened zingo and went to sync report screen
2. i minimised zingo after a few seconds (propbably 1st or 2nd batch) and went to settings to change my display settings to stay open from 30 seconds -> 30 minutes
3. i then went back to zingo and sync report screen said "loading" and then loaded these incorrect stats

**Comment by juanky201271** [comment]
> i wish i had more details but this was what happened:
> 
>     1. i opened zingo and went to sync report screen
> 
>     2. i minimised zingo after a few seconds (propbably 1st or 2nd batch) and went to settings to change my display settings to stay open from 30 seconds -> 30 minutes
> 
>     3. i then went back to zingo and sync report screen said "loading" and then loaded these incorrect stats

For me, this is a really good explanation, I'm going to try these specific steps, I wish I can reproduce it. Thanks.

**Comment by Oscar-Pepper** [comment]
> > i wish i had more details but this was what happened:
> > ```
> > 1. i opened zingo and went to sync report screen
> > 
> > 2. i minimised zingo after a few seconds (propbably 1st or 2nd batch) and went to settings to change my display settings to stay open from 30 seconds -> 30 minutes
> > 
> > 3. i then went back to zingo and sync report screen said "loading" and then loaded these incorrect stats
> > ```
> 
> For me, this is a really good explanation, I'm going to try these specific steps, I wish I can reproduce it. Thanks.

keep in mind that i may be wrong how long zingo was open before i switched to settings... it could have been more batches so worth testing too
