### ISSUE TITLE
Sending errors - some of them need a specific message in UI

### ISSUE THREAD

**Issue by juanky201271** [zingolabs/zingo-mobile#256]
We have some sending error that they are not really bugs... like:

- `64: dust`
- `18: bad-txns-sapling-duplicate-nullifier` (this error is only for `sapling` or exists for `orchard` as well?????)

We need to stop those errors and change them for a really nice message with a good explanation for Aunt Matilda and others users...

@zancas @AloeareV 
Maybe you guys can provide a message for each one, as you know, my English & knowledge are not the best...

**Comment by juanky201271** [comment]
this is related with : https://github.com/zingolabs/zingolib/issues/186

**Comment by AloeareV** [comment]
"18: bad-txns-sapling-duplicate-nullifier" has a similar "bad-txns-orchard-duplicate-nullifier", I don't know the number code off the top of my head. It means one of the sapling notes we attempted to spend has already been spent, at a height above where the wallet's currently synced.

**Comment by AloeareV** [comment]
"64: dust" isn't entirely clear to me, it means that a sent note is below some minimum threshold of value, I think it only applies to transparent outputs. I know we can send shielded notes of 0-zats/1-zat, so there's some specific condition that triggers it, and I _think_ that condition is "sent a tiny value to a taddr" but I'm not confident of that.

**Comment by juanky201271** [comment]
> "18: bad-txns-sapling-duplicate-nullifier" has a similar "bad-txns-orchard-duplicate-nullifier", I don't know the number code off the top of my head. It means one of the sapling notes we attempted to spend has already been spent, at a height above where the wallet's currently synced.

I think the code for those three similar error are the same: https://github.com/zcash/zcash/blob/666a8d1b37d9f17f3351bf07998b980a802126e7/src/main.cpp#L142

And I can see the third one here: https://github.com/zcash/zcash/blob/666a8d1b37d9f17f3351bf07998b980a802126e7/src/main.cpp#L153

**Comment by juanky201271** [comment]
@zancas 
I tried my best writing these two errors...

"duplicate-nullifier-error": `Your funds are still confirming and probably syncing. You can wait until the funds are confirmed or you can try to send now with a lower amount. The Transaction build failed!`,

"dust-error" : `The amount that you are trying to send to a Transparent address is really tiny. The Transaction build failed!`

But I'm not sure about Matilda reading this while she is trying to pay in the supermarket...

If someone are really into in the Spanish version... Aqui esta:

"duplicate-nullifier-error": `Tus fondos están todavía confirmándose y probablemente sincronizándose. Puedes esperar hasta que tus fondos estén confirmados o puedes intentar enviar una cantidad más pequeña, La creaccion de la Transacción ha fallado!`

"dust-error" : `La cantidad que estás intentando enviar a una dirección Transparente is realmente infima, La creaccion de la Transacción ha fallado!`

**Comment by zancas** [comment]
I like the "dust-error" a lot!

For the `duplicate-nullifier-error` I think we have to consider that the meaning of the error is going to to shift significantly soon...
