### ISSUE TITLE
Very cold when changing servers 🥶

### ISSUE THREAD

**Issue by Edicksonjga** [zingolabs/zingo-mobile#288]
The application freezes when trying to change servers with any link.

**Steps:**
1. Enter Parameters from the menu
2. Go to Server and then tap on Other
3. Fill in the field with any link (example: https://z.cash)
4. Touch Save

**How is it working:**
The application freezes when "saving" the changes made.

**How it should work:**
The application should display a warning indicating that the changes cannot be saved because the link is not to a server.

**Demonstration:**
https://user-images.githubusercontent.com/37910384/232277981-d7c1dbcf-03ef-4115-ae86-ac66e7d3b9f6.mp4

**Note**: while recording the previous video, the application showed the error: _"Error trying to read the active wallet using the new server..."_, at the same time a window opens where you must confirm that you want to change servers and invite to make a backup, I will make a new report for this.

**Comment by juanky201271** [comment]
Good point, and I experienced that too when you put an invalid URI... Here I have to put a modal screen while the App is trying to connect with the new `server`. Thanks for this issue.
