### ISSUE TITLE
Server without port/Active Wallet does not exist 😱

### ISSUE THREAD

**Issue by Edicksonjga** [zingolabs/zingo-mobile#289]
I previously reported that the wallet would freeze when using any link when customizing the server parameters.

But, if you use the server binding of ZecWallet or Lightwalletd and don't add a port to it, the app doesn't freeze, show a toast with an error, and pop up a window to confirm and backup.

Note: When the app freezes, after a few seconds/minutes it returns to normal, shows the error, and pops up the window to confirm and backup.

Steps and UX issues:
1. Enter Parameters from Menu
2. Go to the Server options and tap on Others
3. Add the link of a server without adding the port, example:
4. Save the changes

How it's working:
When saving the changes, a toast is displayed indicating an error and a window is immediately opened to confirm the change and make a backup copy.

How it should work:
Instead of a toast/tooltips, the error should be displayed in a pop-up where you can more calmly read what is happening.

Suggestions:
1. The pop-up must indicate the link does not comply with the parameters corresponding to the link of a server.
2. Make ZecWallet server binding connect to port ...:443 by default.
3. The confirmation window should not be displayed if the server link is invalid.

UX issues:

1. This error causes a window to open to confirm the change of server, this window indicates that the new server the account does not exist (alarming that strings 😳).
2. Upon confirmation, the application redirects to the Start window where little or nothing can be done since the user has connected to a server that does not exist/does not work.
2.1 Setting a birthday in Account Restore doesn't work, in fact the string shows a range of values ​​from 1 to (nothing).
3. If the ZecWallet server link is used and no port is set, the auto wallet adds port 9067, the port for ZecWallet is 443.

I have reported similar UX issues on [234](https://github.com/zingolabs/zingo-mobile/issues/234).

Demo:
https://user-images.githubusercontent.com/37910384/232280077-316e23f6-4a5e-4d8a-b9bd-ebb82e688f33.mp4

**Comment by juanky201271** [comment]
Thanks for taking the time to report this issue. Both issues are related, of course, and the solution will be for both.
