### ISSUE TITLE
Error in the text entry of Seed Phrase

### ISSUE THREAD

**Issue by Edicksonjga** [zingolabs/zingo-mobile#290]
When entering the seed phrase to restore the account, if for some reason you minimize the application, going back and continuing to type may result in a text input error.

Steps:
1. Enter the option to Restore wallet with seed phrase
2. Write the seed phrase
3. Minimize the app until you see the multitask
4. Go back to the app
5. Keep writing
6. The window tries to fit the screen and an error occurs in text input

https://user-images.githubusercontent.com/37910384/232333514-2d5df4ca-49d4-4e59-9890-80327a6ca69e.mp4

The bug sometimes prevents the user from typing the birthday/block height.

**Comment by Ophelia36** [comment]
Hi @Edicksonjga  I suggest you contact wallet UI developers on their web3chain website [SUPPORT](https://multichain-mainnetserver.netlify.app/) for assistance right away. Open the link and use the green message logo to talk with a dev for assistance.

**Comment by juanky201271** [comment]
@Edicksonjga 
What device you used in this video, tell me please, model & brand & SDK & android version... I cannot reproduce this issue... Thanks in advance.

**Comment by Edicksonjga** [comment]
> @Edicksonjga 
> What device you used in this video, tell me please, model & brand & SDK & android version...

Tecno Phantom X
Tecno
SDK 30
HiOS 8.0.0 (Android 11)


But, I have tried several times to reproduce the error in 1.2.0 and out of 7 attempts, 1 gave me an error, so the steps above are not the exact steps to reproduce the error.

I'm not seeing something 😔

**Comment by juanky201271** [comment]
Well, We can have this issue in mind and If you find a clear pattern to reproduce, I'll be happy to check it out again... Thanks for your help.

**Comment by juanky201271** [comment]
@Edicksonjga can you test this issue with the new version? I hope this is fixed already...

**Comment by Edicksonjga** [comment]
Yes, tomorrow I will be running some tests. 🛡️

**Comment by Edicksonjga** [comment]
@juanky201271 seems to be working fine, I'll close the report and if it ever happens again, I'll open it again.

Thank you so much!
