### ISSUE TITLE
Android Test v121 - [split_config.arm64_v8a.apk] std::sys::unix::abort_internal::h5babf996378fb434

### ISSUE THREAD

**Issue by juanky201271** [zingolabs/zingo-mobile#301]
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 0, tid: 15470 >>> org.ZingoLabs.Zingo <<<

backtrace:
  #00  pc 0x000000000004e574  /apex/com.android.runtime/lib64/bionic/libc.so (abort+180)
  #01  pc 0x000000000509f9e8  /data/app/~~5lBv0Em7FREXvCp61sWbeQ==/org.ZingoLabs.Zingo-NSbrCw6sU8DuXXNgc4FuCg==/split_config.arm64_v8a.apk (std::sys::unix::abort_internal::h5babf996378fb434+4)
  #02  pc 0x0000000005096fd0  /data/app/~~5lBv0Em7FREXvCp61sWbeQ==/org.ZingoLabs.Zingo-NSbrCw6sU8DuXXNgc4FuCg==/split_config.arm64_v8a.apk (rust_panic+128)
  #03  pc 0x0000000005096dcc  /data/app/~~5lBv0Em7FREXvCp61sWbeQ==/org.ZingoLabs.Zingo-NSbrCw6sU8DuXXNgc4FuCg==/split_config.arm64_v8a.apk (std::panicking::rust_panic_with_hook::h4289778276858d77+668)
  #04  pc 0x00000000050c9158  /data/app/~~5lBv0Em7FREXvCp61sWbeQ==/org.ZingoLabs.Zingo-NSbrCw6sU8DuXXNgc4FuCg==/split_config.arm64_v8a.apk
  #05  pc 0x00000000050c82dc  /data/app/~~5lBv0Em7FREXvCp61sWbeQ==/org.ZingoLabs.Zingo-NSbrCw6sU8DuXXNgc4FuCg==/split_config.arm64_v8a.apk
  #06  pc 0x0000000005096938  /data/app/~~5lBv0Em7FREXvCp61sWbeQ==/org.ZingoLabs.Zingo-NSbrCw6sU8DuXXNgc4FuCg==/split_config.arm64_v8a.apk (rust_begin_unwind+108)
  #07  pc 0x000000000513c5cc  /data/app/~~5lBv0Em7FREXvCp61sWbeQ==/org.ZingoLabs.Zingo-NSbrCw6sU8DuXXNgc4FuCg==/split_config.arm64_v8a.apk (core::panicking::panic_fmt::h18bdfd1f523ee1e1+44)
  #08  pc 0x000000000513c9d4  /data/app/~~5lBv0Em7FREXvCp61sWbeQ==/org.ZingoLabs.Zingo-NSbrCw6sU8DuXXNgc4FuCg==/split_config.arm64_v8a.apk (core::result::unwrap_failed::hf7599ff13133c156+84)
  #09  pc 0x00000000040aeed8  /data/app/~~5lBv0Em7FREXvCp61sWbeQ==/org.ZingoLabs.Zingo-NSbrCw6sU8DuXXNgc4FuCg==/split_config.arm64_v8a.apk
  #10  pc 0x00000000042ba320  /data/app/~~5lBv0Em7FREXvCp61sWbeQ==/org.ZingoLabs.Zingo-NSbrCw6sU8DuXXNgc4FuCg==/split_config.arm64_v8a.apk
  #11  pc 0x0000000004307948  /data/app/~~5lBv0Em7FREXvCp61sWbeQ==/org.ZingoLabs.Zingo-NSbrCw6sU8DuXXNgc4FuCg==/split_config.arm64_v8a.apk
  #12  pc 0x0000000004051dec  /data/app/~~5lBv0Em7FREXvCp61sWbeQ==/org.ZingoLabs.Zingo-NSbrCw6sU8DuXXNgc4FuCg==/split_config.arm64_v8a.apk (zingolib::get_latest_block_height::hcf242c9e14ac76bf+148)
  #13  pc 0x0000000003ec1e8c  /data/app/~~5lBv0Em7FREXvCp61sWbeQ==/org.ZingoLabs.Zingo-NSbrCw6sU8DuXXNgc4FuCg==/split_config.arm64_v8a.apk
  #14  pc 0x0000000003ec24e4  /data/app/~~5lBv0Em7FREXvCp61sWbeQ==/org.ZingoLabs.Zingo-NSbrCw6sU8DuXXNgc4FuCg==/split_config.arm64_v8a.apk (rustlib::init_from_b64::hc47eb7e3d7cc92fb+72)
  #15  pc 0x0000000003ebcc98  /data/app/~~5lBv0Em7FREXvCp61sWbeQ==/org.ZingoLabs.Zingo-NSbrCw6sU8DuXXNgc4FuCg==/split_config.arm64_v8a.apk (Java_org_ZingoLabs_Zingo_RustFFI_00024Companion_initfromb64+456)
  #16  pc 0x000000000005e7b0  /data/app/~~5lBv0Em7FREXvCp61sWbeQ==/org.ZingoLabs.Zingo-NSbrCw6sU8DuXXNgc4FuCg==/oat/arm64/base.odex

**Comment by juanky201271** [comment]
Android 11 SDK 30.

I can see this:  `(zingolib::get_latest_block_height::hcf242c9e14ac76bf+148)`

**Comment by juanky201271** [comment]
The same problem with a longer log:
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 0, tid: 22590 >>> org.ZingoLabs.Zingo <<<

backtrace:
  #00  pc 0x000000000004e574  /apex/com.android.runtime/lib64/bionic/libc.so (abort+180)
  #01  pc 0x000000000509f9e8  /data/app/~~5lBv0Em7FREXvCp61sWbeQ==/org.ZingoLabs.Zingo-NSbrCw6sU8DuXXNgc4FuCg==/split_config.arm64_v8a.apk (std::sys::unix::abort_internal::h5babf996378fb434+4)
  #02  pc 0x0000000005096fd0  /data/app/~~5lBv0Em7FREXvCp61sWbeQ==/org.ZingoLabs.Zingo-NSbrCw6sU8DuXXNgc4FuCg==/split_config.arm64_v8a.apk (rust_panic+128)
  #03  pc 0x0000000005096dcc  /data/app/~~5lBv0Em7FREXvCp61sWbeQ==/org.ZingoLabs.Zingo-NSbrCw6sU8DuXXNgc4FuCg==/split_config.arm64_v8a.apk (std::panicking::rust_panic_with_hook::h4289778276858d77+668)
  #04  pc 0x00000000050c9158  /data/app/~~5lBv0Em7FREXvCp61sWbeQ==/org.ZingoLabs.Zingo-NSbrCw6sU8DuXXNgc4FuCg==/split_config.arm64_v8a.apk
  #05  pc 0x00000000050c82dc  /data/app/~~5lBv0Em7FREXvCp61sWbeQ==/org.ZingoLabs.Zingo-NSbrCw6sU8DuXXNgc4FuCg==/split_config.arm64_v8a.apk
  #06  pc 0x0000000005096938  /data/app/~~5lBv0Em7FREXvCp61sWbeQ==/org.ZingoLabs.Zingo-NSbrCw6sU8DuXXNgc4FuCg==/split_config.arm64_v8a.apk (rust_begin_unwind+108)
  #07  pc 0x000000000513c5cc  /data/app/~~5lBv0Em7FREXvCp61sWbeQ==/org.ZingoLabs.Zingo-NSbrCw6sU8DuXXNgc4FuCg==/split_config.arm64_v8a.apk (core::panicking::panic_fmt::h18bdfd1f523ee1e1+44)
  #08  pc 0x000000000513c9d4  /data/app/~~5lBv0Em7FREXvCp61sWbeQ==/org.ZingoLabs.Zingo-NSbrCw6sU8DuXXNgc4FuCg==/split_config.arm64_v8a.apk (core::result::unwrap_failed::hf7599ff13133c156+84)
  #09  pc 0x00000000040aeed8  /data/app/~~5lBv0Em7FREXvCp61sWbeQ==/org.ZingoLabs.Zingo-NSbrCw6sU8DuXXNgc4FuCg==/split_config.arm64_v8a.apk
  #10  pc 0x00000000042ba320  /data/app/~~5lBv0Em7FREXvCp61sWbeQ==/org.ZingoLabs.Zingo-NSbrCw6sU8DuXXNgc4FuCg==/split_config.arm64_v8a.apk
  #11  pc 0x0000000004307948  /data/app/~~5lBv0Em7FREXvCp61sWbeQ==/org.ZingoLabs.Zingo-NSbrCw6sU8DuXXNgc4FuCg==/split_config.arm64_v8a.apk
  #12  pc 0x0000000004051dec  /data/app/~~5lBv0Em7FREXvCp61sWbeQ==/org.ZingoLabs.Zingo-NSbrCw6sU8DuXXNgc4FuCg==/split_config.arm64_v8a.apk (zingolib::get_latest_block_height::hcf242c9e14ac76bf+148)
  #13  pc 0x0000000003ec1e8c  /data/app/~~5lBv0Em7FREXvCp61sWbeQ==/org.ZingoLabs.Zingo-NSbrCw6sU8DuXXNgc4FuCg==/split_config.arm64_v8a.apk
  #14  pc 0x0000000003ec24e4  /data/app/~~5lBv0Em7FREXvCp61sWbeQ==/org.ZingoLabs.Zingo-NSbrCw6sU8DuXXNgc4FuCg==/split_config.arm64_v8a.apk (rustlib::init_from_b64::hc47eb7e3d7cc92fb+72)
  #15  pc 0x0000000003ebcc98  /data/app/~~5lBv0Em7FREXvCp61sWbeQ==/org.ZingoLabs.Zingo-NSbrCw6sU8DuXXNgc4FuCg==/split_config.arm64_v8a.apk (Java_org_ZingoLabs_Zingo_RustFFI_00024Companion_initfromb64+456)
  #16  pc 0x00000000000c27b0  /data/app/~~5lBv0Em7FREXvCp61sWbeQ==/org.ZingoLabs.Zingo-NSbrCw6sU8DuXXNgc4FuCg==/oat/arm64/base.odex (art_jni_trampoline+208)
  #17  pc 0x00000000002c2efc  /data/app/~~5lBv0Em7FREXvCp61sWbeQ==/org.ZingoLabs.Zingo-NSbrCw6sU8DuXXNgc4FuCg==/oat/arm64/base.odex (org.ZingoLabs.Zingo.RPCModule.loadExistingWallet+1948)
  #18  pc 0x0000000000134564  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+548)
  #19  pc 0x00000000001aa7e8  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+200)
  #20  pc 0x000000000055fdfc  /apex/com.android.art/lib64/libart.so (art::InvokeMethod(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jobject*, _jobject*, unsigned long)+1364)
  #21  pc 0x00000000004de560  /apex/com.android.art/lib64/libart.so (art::Method_invoke(_JNIEnv*, _jobject*, _jobject*, _jobjectArray*)+48)
  #22  pc 0x00000000000896f4  /apex/com.android.art/javalib/arm64/boot.oat (art_jni_trampoline+180)
  #23  pc 0x00000000001efe00  /data/app/~~5lBv0Em7FREXvCp61sWbeQ==/org.ZingoLabs.Zingo-NSbrCw6sU8DuXXNgc4FuCg==/oat/arm64/base.odex (com.facebook.react.bridge.JavaMethodWrapper.invoke+1712)
  #24  pc 0x000000000015b748  /data/app/~~5lBv0Em7FREXvCp61sWbeQ==/org.ZingoLabs.Zingo-NSbrCw6sU8DuXXNgc4FuCg==/oat/arm64/base.odex (com.facebook.react.bridge.JavaModuleWrapper.invoke+1304)
  #25  pc 0x0000000000134564  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+548)
  #26  pc 0x00000000001aa7e8  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+200)
  #27  pc 0x000000000055f6dc  /apex/com.android.art/lib64/libart.so (art::JValue art::InvokeVirtualOrInterfaceWithVarArgs<art::ArtMethod*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, art::ArtMethod*, std::__va_list)+468)
  #28  pc 0x000000000055f87c  /apex/com.android.art/lib64/libart.so (art::JValue art::InvokeVirtualOrInterfaceWithVarArgs<_jmethodID*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, std::__va_list)+92)
  #29  pc 0x00000000003b1df0  /apex/com.android.art/lib64/libart.so (art::JNI<false>::CallVoidMethodV(_JNIEnv*, _jobject*, _jmethodID*, std::__va_list)+656)
  #30  pc 0x0000000000060eb4  /data/app/~~5lBv0Em7FREXvCp61sWbeQ==/org.ZingoLabs.Zingo-NSbrCw6sU8DuXXNgc4FuCg==/split_config.arm64_v8a.apk!libreactnativejni.so (_JNIEnv::CallVoidMethod(_jobject*, _jmethodID*, ...)+116)
  #31  pc 0x000000000006fee4  /data/app/~~5lBv0Em7FREXvCp61sWbeQ==/org.ZingoLabs.Zingo-NSbrCw6sU8DuXXNgc4FuCg==/split_config.arm64_v8a.apk!libreactnativejni.so
  #32  pc 0x0000000000068ee8  /data/app/~~5lBv0Em7FREXvCp61sWbeQ==/org.ZingoLabs.Zingo-NSbrCw6sU8DuXXNgc4FuCg==/split_config.arm64_v8a.apk!libreactnativejni.so
  #33  pc 0x000000000000f80c  /data/app/~~5lBv0Em7FREXvCp61sWbeQ==/org.ZingoLabs.Zingo-NSbrCw6sU8DuXXNgc4FuCg==/split_config.arm64_v8a.apk!libfbjni.so (facebook::jni::detail::MethodWrapper<void (facebook::jni::JNativeRunnable::*)(), &(facebook::jni::JNativeRunnable::run()), facebook::jni::JNativeRunnable, void>::dispatch(facebook::jni::alias_ref<facebook::jni::detail::JTypeFor<facebook::jni::HybridClass<facebook::jni::JNativeRunnable, facebook::jni::JRunnable>::JavaPart, facebook::jni::JRunnable, void>::_javaobject*>)+32)
  #34  pc 0x000000000000f778  /data/app/~~5lBv0Em7FREXvCp61sWbeQ==/org.ZingoLabs.Zingo-NSbrCw6sU8DuXXNgc4FuCg==/split_config.arm64_v8a.apk!libfbjni.so (facebook::jni::detail::FunctionWrapper<void (*)(facebook::jni::alias_ref<facebook::jni::detail::JTypeFor<facebook::jni::HybridClass<facebook::jni::JNativeRunnable, facebook::jni::JRunnable>::JavaPart, facebook::jni::JRunnable, void>::_javaobject*>), facebook::jni::detail::JTypeFor<facebook::jni::HybridClass<facebook::jni::JNativeRunnable, facebook::jni::JRunnable>::JavaPart, facebook::jni::JRunnable, void>::_javaobject*, void>::call(_JNIEnv*, _jobject*, void (*)(facebook::jni::alias_ref<facebook::jni::detail::JTypeFor<facebook::jni::HybridClass<facebook::jni::JNativeRunnable, facebook::jni::JRunnable>::JavaPart, facebook::jni::JRunnable, void>::_javaobject*>))+60)
  #35  pc 0x00000000000be8bc  /data/app/~~5lBv0Em7FREXvCp61sWbeQ==/org.ZingoLabs.Zingo-NSbrCw6sU8DuXXNgc4FuCg==/oat/arm64/base.odex (art_jni_trampoline+124)
  #36  pc 0x00000000006564bc  /system/framework/arm64/boot-framework.oat (android.os.Handler.dispatchMessage+76)
  #37  pc 0x0000000000164244  /data/app/~~5lBv0Em7FREXvCp61sWbeQ==/org.ZingoLabs.Zingo-NSbrCw6sU8DuXXNgc4FuCg==/oat/arm64/base.odex (com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage+52)
  #38  pc 0x0000000000659abc  /system/framework/arm64/boot-framework.oat (android.os.Looper.loop+1692)
  #39  pc 0x0000000000164438  /data/app/~~5lBv0Em7FREXvCp61sWbeQ==/org.ZingoLabs.Zingo-NSbrCw6sU8DuXXNgc4FuCg==/oat/arm64/base.odex (com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run+312)
  #40  pc 0x000000000015b358  /apex/com.android.art/javalib/arm64/boot.oat (java.lang.Thread.run+72)
  #41  pc 0x0000000000134564  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+548)
  #42  pc 0x00000000001aa7e8  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+200)
  #43  pc 0x000000000055f36c  /apex/com.android.art/lib64/libart.so (art::JValue art::InvokeVirtualOrInterfaceWithJValues<art::ArtMethod*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, art::ArtMethod*, jvalue const*)+460)
  #44  pc 0x00000000005af6b4  /apex/com.android.art/lib64/libart.so (art::Thread::CreateCallback(void*)+1308)
  #45  pc 0x00000000000b0838  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+64)
  #46  pc 0x00000000000505d0  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64)

**Comment by AloeareV** [comment]
Whoa. I'm guessing that you lost connection to the lightwalletd at the wrong moment...but this is a bug in zingolib that it's causing a panic instead of a smoother error. I'll look into it!

**Comment by juanky201271** [comment]
old, closing.
