### ISSUE TITLE
Crash when using http links as server

### ISSUE THREAD

**Issue by Edicksonjga** [zingolabs/zingo-mobile#304]
Application crashes when configuring a "server" with _http_ binding.

**Steps:**
1. Enter the app and go to the menu
2. Tap on Settings
3. Go to server settings
4. Select Custom
5. Paste the http link
6. Touch Save

**How it should work:**
The application should throw an error indicating that the _http_ link is invalid.

**How it's working:**
The application closes (crash) when you tap save.

https://user-images.githubusercontent.com/37910384/234717734-fcb4bacc-85bb-4b84-90d1-c26d004791dc.mp4

**Device and version of Wallet:**
Techno Phantom X
HiOS 8.0 (Android 11/SDK 30)
Zingo Beta 1.2.0 (121)

**Comment by juanky201271** [comment]
yes, this problem is fixed in this PR: #291 Thanks for reporting...
