### ISSUE TITLE
Opening another wallet returns you to the active wallet

### ISSUE THREAD

**Issue by Edicksonjga** [zingolabs/zingo-mobile#307]
The app does not stay on the Home screen (Create Account/Restore Wallet) when closed in the background.

Steps:
1. Tap on Switch to another wallet from Settings
2. Tap on Restore wallet
3. Close the background app or switch apps and come back a few minutes later
4. The wallet that was active opens

I'm not sure why it happens, the error appears sometimes, but I think the expected behavior is to keep the Home screen to restore or create another wallet, which is the action the user took at the beginning.

Videos demonstration:
https://user-images.githubusercontent.com/37910384/234996787-b9253d16-dcee-43ac-86b7-d1f6f7bd4a76.mp4

https://user-images.githubusercontent.com/37910384/234997046-c42ade70-e1c3-41ed-ba93-1d90eaac3de3.mp4

**Comment by juanky201271** [comment]
Thanks for the info, I was working in a fix for this....
