### ISSUE TITLE

Keyboard doesn't close quickly/white background

### ISSUE THREAD

**Issue by Edicksonjga** [zingolabs/zingo-mobile#308]
When you open the keyboard inside the application you can see a white background (below the keyboard), if you change servers to a custom one or Restore a wallet, the keyboard is not hidden quickly.

"Certain processes are heavier and block the user interface, ...and the screen is not recomposed without the keyboard."

https://user-images.githubusercontent.com/37910384/234999250-b33a633e-1d36-458b-a667-68d62f40b788.mp4

![Screenshot_20230427-161103.jpg](https://user-images.githubusercontent.com/37910384/234999277-7de039e4-a3b2-41c8-8f23-b749c1e61574.jpg)

**Comment by juanky201271** [comment]
Yes, you are right, I noticed sometimes about this behavior... I'm going to look into this ASAP.

Thanks @Edicksonjga
