### ISSUE TITLE
Trying to Shield a small amount of transparent funds

### ISSUE THREAD

**Issue by juanky201271** [zingolabs/zingo-mobile#329]
I have:
- sapling pool: 1000 zats. (for the fee)
- transparent pool: 1000 zats. (for shielding)

An I got this error:
`"error": "Not enough transparent balance to shield. Have 1000 zats, need more than 1000 zats to cover tx fee"`

Well, I can cover the fee with my sapling funds... do I need to have 1000 (minimum) + 1000 (fee) = 2000 zats to shiled my funds????

**Comment by AloeareV** [comment]
Shield operations will only spend from the transparent pool (including only paying fees with funds from the transparent pool), and it won't let you send 0. (As the fee is now 10_000), you need at least 10_001 zats in the transparent pool to shield.

**Comment by juanky201271** [comment]
Thanks... that make sense... closing...
