### ISSUE TITLE
Production version 1.2.1 (122) - Testnet server

### ISSUE THREAD

**Issue by juanky201271** [zingolabs/zingo-mobile#341]
I changed the server to a custom one: `https://testnet.lightwalletd.com:9067` and I can see the new server in `Server Info` but the `server block height` is 2335886 (mainnet) and I keep using my wallet from mainnet too.

This is weird, and confusing... Ref: https://github.com/zingolabs/zingo-mobile/issues/321

This is something we have to fix/change soon.

@zancas @AloeareV @fluidvanadium @Oscar-Pepper

**Comment by juanky201271** [comment]
First experience with this: I changed my App to a custom server `testnet`, and the wallet, for some reason, is not able to sync anymore, and the spendable balance is 0 for all of the pools... my next move was: I'm going to restore a `mainnet` server... and the result was, the same... my wallet is useless. My only option here was rescan the wallet from the beginnig.

NOTE: I changed to another wallet and I created a new wallet and everythig was working... I guess the problem was in my wallet file in my device, not in the App itself...

**Comment by juanky201271** [comment]
This is the error I get with this wallet: `Server's latest block(2079312) is behind ours(2205745)`

I don't know how, my wallet file have a height block 126.433 blocks more than the server... make any sense?

**Comment by zancas** [comment]
You can't use a wallet from `mainnet` with a `testnet` blockchain.   They're incompatible.

**Comment by juanky201271** [comment]
> You can't use a wallet from `mainnet` with a `testnet` blockchain. They're incompatible.

well, I know that... but if a user change the server to testnet.... `catapummmm`.

**Comment by juanky201271** [comment]
My final thought is: If Zingo allow to the user (advance, basic, Gizelda or Pepe Perez) to change to a custom server (whatever URI), we cannot know the chain_type of that URI without interact before with the URI...

- The App allow to the user to put: https.........testnet........ (a valid testnet server)
- And the App have `zingoconfig::ChainType::Mainnet` harcoded....

I feel like this is a dangerous situation...

**Comment by zancas** [comment]
This is a good point.   We can upgrade from hard-coded mainnet.

I think it would be fine to force choosing testnet to require several User ceremonies:

* check the testnet box
* enter the name of a testnet server

**Comment by juanky201271** [comment]
I can prevent this happens... because I can compare the `info` between the actual server & the new server, and in this case I can do the same that when in this situation the App cannot open the current wallet with the new server...

I'm going to start working on this right now... I just have an epiphany... I want to follow it.
