### ISSUE TITLE
Sent-to-self Transaction with a weird fee

### ISSUE THREAD

**Issue by juanky201271** [zingolabs/zingo-mobile#361]
I got this tx:
`LOG  tran:  {"amount": -4000, "block_height": 1840793, "datetime": 1665604310, "outgoing_metadata": [], "txid": "d902ac513e23761b36a9edf7191f4cb984525884c4982b39e8e5de1791fdc47b", "unconfirmed": false, "zec_price": null}'

My question is: if the only number field is amount -> -4000 zats, in the tx... make any sense to show the transaction fee as: 4000 zats? or in this edge cases is better to hide the fee?

And I got several of these txs... but those are in a old wallet... but I want to know the best way to visualize this kind of weird cases...

My seconds question is: in this kind of txs with no address as well... what is the best option: to put Unknown (this is the actual behavior) or to put the UA or Sapling addr or Transparent addr????? or maybe a third option: to put nothing at all...

**Comment by AloeareV** [comment]
The lack of address indicates that this was a send-to-self with no memo, so we consider it to be change. I'm not sure how a transaction with a fee of 4000 zats was created, but it's totally allowable at the protocol level, and I think at some point we had an interface somewhere with option to supply a custom fee. The zcash block explorer indicates that this is a transaction with 1/2 shielded inputs/outputs, 2 orchard actions, and a fee paid of 4000 zats. 

The existence of this transaction is a bit confusing to me, but as far as I can tell, displaying it as a transaction with a fee of 4000 zats is correct. I think leaving as `Unknown` is confusing, but probably fine in the short term.

Ideally I would like to replace the transactions display with a value_transfer display, using the new `txsummaries` command, but that will be a decent bit of UI work on your end and it's not in any way urgent.

**Comment by juanky201271** [comment]
Thank you for the info. I'm sure this can be better in some future with the new command: `txsummaries`.

**Comment by juanky201271** [comment]
We are working now in `summaries`, this issue make no sense in this moment, closing...
