### ISSUE TITLE
Greater privacy in transactions

### ISSUE THREAD

**Issue by Edicksonjga** [zingolabs/zingo-mobile#363]
Zingo (including Zingo-PC) does not manage the funds that are in the Sapling shield pool towards Sapling (when the unified address is complete), it sends the funds towards Orchard.

This causes the transaction to not be totally private, when a transaction is of type z2u or u2z they reveal the net change of funds that resulted from the transaction.

**Hypothetical case 1:**

1. User A has funds in Sapling and Orchard.
2. User B provides you with a complete unified address.
3. User A proceeds to send ZEC.
4. The wallet sends everything to Orchard and does not take advantage of the recipients of the full unified address, the net change in funds that resulted from the transaction is revealed.

![Screenshot_20230519-232204.jpg](https://github.com/zingolabs/zingo-pc/assets/37910384/6ecb1cd1-83ea-4145-bcd8-3a146bfadba0)
[Blockchain transaction](https://3xpl.com/zcash/transaction/798227db23e1115357feadaa286561a49c7c6cbd34590d647d4f0dd094d617e4).

**Expected behavior:**

The wallet should take advantage of using unified addresses and send funds from Sapling > Sapling and Orchard > Orchard in the transaction. In this way, no information is revealed and the transaction is completely private.

**Hypothetical case 2:**

1. User A has funds in Sapling.
2. User B provides a complete unified address.
3. User A proceeds to send ZEC.
4. The wallet sends the ZECs to Orchard, the net change in funds that resulted from the transaction is revealed.

![IMG_20230519_232513_322.jpg](https://github.com/zingolabs/zingo-pc/assets/37910384/9c4828e6-1404-40e8-88c4-9bd7d5f2c785)

![Screenshot_20230519-232553.jpg](https://github.com/zingolabs/zingo-pc/assets/37910384/0ec53443-f2bc-48a3-a3dd-dbe94539febd)
[Blockchain transaction](https://3xpl.com/zcash/transaction/c15fb07a737033bc542b83068aed669cf6f1695021d4f39ff77bb465f1a36375).

**Expected behavior:**

The wallet should take advantage of the recipients of the unified address to make the transaction as private as possible. In this case he should have sent to Sapling.

**Suggestion 1:**
I think it would be nice to make a change where the fund manager always takes advantage of the unified address shield receivers to keep the transaction as private as possible if the sending user has the necessary funds to complete the transaction privately.

**Suggestion 2:**
Add a transaction confirmation screen where the user can see the level of privacy of their transaction, in Zingo-PC it can be seen, but not in Zingo for mobile devices.

From Zingo-PC you can see from the confirmation pop-up window if the transaction is shielded, reveals the amount or is public.

I don't know why, but Zingo also automatically migrates funds from Sapling to Orchard when a transaction is made. I guess it is due to the automatic funds migration and shielding function to the last shielded pool added in NU5.

**Comment by zancas** [comment]
I agree that Zingo MUST never leak information without explicit opt-in from the User.

We'll upgrade our policy to handle the Sapling case in a more nuanced way.

We'll also be upgrading the UI to encourage the User to migrate to Orchard (Shield-To-Orchard) whenever the Sapling Balance is Non-Zero, and we'll encourage the User to request an Orchard receiver whenever they are offered Sapling.

**Comment by AloeareV** [comment]
We send to orchard in compliance with [zip316](https://zips.z.cash/zip-0316#encoding-of-unified-addresses), which obligates senders to send to orchard if the UA has an orchard component. (zip316 is not part of consensus, so we can ignore `MUST`s if we truly deem in necessary, but if so I want to have well-documented reasons, and a PR into the zips repo that tries to change it)

"The Sender of a payment to a Unified Address MUST use the Receiver of the most preferred Receiver Type that it supports from the set.

"For example, consider a wallet that supports sending funds to Orchard Receivers, and does not support sending to any Receiver Type that is preferred over Orchard. If that wallet is given a UA that includes an Orchard Receiver and possibly other Receivers, it MUST send to the Orchard Receiver."

I agree that this has unfortunate privacy implications. A possible short-term improvement could be to prioritize spending orchard funds if sending to orchard, and sapling funds if sending to sapling. 

I have some work on a more privacy-aware note selection algorithm [here](https://github.com/AloeareV/zingolib/tree/improve_note_selection). It would bring zingolib's privacy properties in line with zcashd's. There's a good deal of work that would need to be done on the mobile/UI side to go along with it. It's not in a concrete spot in our timeline, but it's work I would like to complete at some point.

**Comment by juanky201271** [comment]
Sounds promising & interesting... I'm all ears about the UI implications... but I think, for now we have another matters to deal with. Thanks @Edicksonjga for your analysis.
