### ISSUE TITLE
QR code scanner screen - Square

### ISSUE THREAD

**Issue by juanky201271** [zingolabs/zingo-mobile#373]
I think we need to help a little bit to user to scan the QR code adding a Square in this screen, because we know when the QR code is in the middle of the screen the App is able to read it better and faster.

@Oscar-Pepper have this idea because he said that he can spent about 14 seconds to scan a QR.

**Comment by Edicksonjga** [comment]
I totally agree, I was seconds away from reporting this hahaha.

Last weekend I was using Zingo with some friends and yes, scanning the QR code took a few seconds. Some guides (square in the center) is a good solution.
