### ISSUE TITLE
Suggestion for High Privacy and Normal

### ISSUE THREAD

**Issue by Edicksonjga** [zingolabs/zingo-mobile#380]
The text on the button to switch between High Privacy and Normal Privacy causes a visual error (bug🐛) on some devices.

Steps:

1. Open in to Zingo Wallet
2. Go to the button that allows you to hide sensitive information
3. You can see that the word **Privacy** is very close to the logo (especially in spanish: **Privacidad**).

On devices with small screens it can be seen over the Zingo logo.

![IMG_20230601_231012_817.jpg](https://github.com/zingolabs/zingo-mobile/assets/37910384/145b0205-70e5-40b4-8719-1d5cd8066c0a)

![Screenshot_20230601-211119.jpg](https://github.com/zingolabs/zingo-mobile/assets/37910384/2232cb84-0db8-4c1b-bc7b-cb20d212eab1)

**Suggestion:**

Delete the word **Privacy** and leave the button: [Normal 🔓] / [High 🔒], or leave only the icons [🔒] / [🔓] and add **tooltips** that are displayed when touching them.

Zingo Wallet v.1.2.2

**Devices:**
Redmi 9A
Techno Phantom X
Android 11

**Comment by juanky201271** [comment]
Thanks for the issue, I fixed/reduce the `Privacidad` text to: `Priv`, fixed in this PR: #379.
