### ISSUE TITLE
BUG: The port is changed automatically

### ISSUE THREAD

**Issue by Edicksonjga** [zingolabs/zingo-mobile#381]
When trying to set a custom server with a port  other than `9067` the port is changed.

Steps:

1. Open Zingo Wallet and enter **Settings** from the Menu
2. Go to Server and set up a custom server
3. Add a different port than `9067`
4. Save
5. The port automatically changes to `9067`

**Expected behavior**
The port should not change and the exact settings you are customizing should be saved

**Current behavior**
The port changes when in the customization it is different from 9067, even with any binding.

https://github.com/zingolabs/zingo-mobile/assets/37910384/9a574190-b578-4289-afad-5ad518e7a8cf

https://github.com/zingolabs/zingo-mobile/assets/37910384/fe422ec1-b476-4e8b-b420-d8bd4436b280

_Zingo Wallet 1.2.2_

**Device:**
Techno Phantom X
Android 11

**Comment by juanky201271** [comment]
Thanks for the issue... the URI parser is not working properly for standard ports like https - 443 or http - 80. FIxed in this PR: #379
