### ISSUE TITLE
Unified Testnet addresses are not being created

### ISSUE THREAD

**Issue by Edicksonjga** [zingolabs/zingo-mobile#384]
**Zingo Mobile** allows you to connect to a `Testnet` network by customizing the server from _Menu > Settings > Server_

Zingo! when connecting to the `testnet` and creating a wallet should generate unified test addresses `utest...`

This is not happening and the unified addresses are **the same as in mainnet**.

**Support images:**
![Screenshot_20230602-215946.jpg](https://github.com/zingolabs/zingo-mobile/assets/37910384/c428f3ba-1d9d-4c4a-8b6e-36ae2e0a3fd1)

![Screenshot_20230602-222527.jpg](https://github.com/zingolabs/zingo-mobile/assets/37910384/dc022b4b-d6c4-4523-8383-3db5d7ff47c4)

![Screenshot_20230602-215942.jpg](https://github.com/zingolabs/zingo-mobile/assets/37910384/267f81e3-0340-47c2-bc4f-7bb2f3980606)

**Related:**
#321

**zingo-cli** does generate unified test addresses, but this is not the case in Zingo Mobile. 🤔

**Comment by juanky201271** [comment]
@Edicksonjga Now this is fixed. When you change a custom server you need to specify the `chain_name`, this way the user decide what kind of addresses the App is going to see...

**Comment by Edicksonjga** [comment]
> @Edicksonjga Now this is fixed. When you change a custom server you need to specify the `chain_name`, this way the user decide what kind of addresses the App is going to see... 

Excellent @juanky201271 , thanks for fixing the bug. 😎👍

**Comment by juanky201271** [comment]
Thank you too, closing...

**Comment by juanky201271** [comment]
Thank you too, closing...
