### ISSUE TITLE
'change to another wallet' warning message

### ISSUE THREAD

**Issue by Oscar-Pepper** [zingolabs/zingo-mobile#390]
i dont want to post an image because it has my seed on this screen but when you select Change to another wallet it says:
"YOU WILL HAVE NO LONGER ACCESS TO THIS WALLET, AND YOU ARE GOING TO ACCESS TO ANOTHER DIFFERENT WALLET"
i think it should read:
"IF YOU CONTINUE, YOU WILL NO LONGER HAVE ACCESS TO THIS WALLET WITHOUT THE SEED PHRASE"

**Comment by juanky201271** [comment]
@Oscar-Pepper
These are three similar messages, maybe you can help with all of them:

* "change-warning": 
"YOU WILL HAVE NO LONGER ACCESS TO THIS WALLET, AND YOU ARE GOING TO ACCESS TO ANOTHER DIFFERENT WALLET",

* "backup-warning": 
"YOU WILL HAVE NO LONGER ACCESS TO THIS WALLET, AND YOU ARE GOING TO ACCESS TO YOUR BACKUP WALLET",

* "server-warning": 
"YOU WILL HAVE NO LONGER ACCESS TO THIS WALLET, AND YOU ARE GOING TO CHANGE TO ANOTHER SERVER IN WHICH YOUR ACTUAL WALLET DOESN'T EXIST",

**Comment by Oscar-Pepper** [comment]
i think we either use this message for all:
"IF YOU CONTINUE, YOU WILL NO LONGER HAVE ACCESS TO THIS WALLET WITHOUT THE SEED PHRASE"
or to be more specific we could say:

    "change-warning":
    "IF YOU CHANGE TO ANOTHER WALLET, YOU WILL NO LONGER HAVE ACCESS TO THIS WALLET WITHOUT THE SEED PHRASE"

    "backup-warning":
    "IF YOU CHANGE TO YOUR BACKUP WALLET, YOU WILL NO LONGER HAVE ACCESS TO THIS WALLET WITHOUT THE SEED PHRASE"

    "server-warning":
    "IF YOU CHANGE TO ANOTHER SERVER, YOU WILL NO LONGER HAVE ACCESS TO THIS WALLET WITHOUT THE SEED PHRASE"

what do you think?

**Comment by AloeareV** [comment]
> ```
> "server-warning":
> "IF YOU CHANGE TO ANOTHER SERVER, YOU WILL NO LONGER HAVE ACCESS TO THIS WALLET WITHOUT THE SEED PHRASE"
> ```

I think this one should specify `IF YOU CHANGE TO A SERVER WITH A DIFFERENT CHAIN`.. Does this message pop up after they enter the server? i.e., do we know what chain they're connecting to? It shouldn't remove the wallet to connect to a different server that's serving the same blockchain, only switching between mainnet/testnet/regtest (although each regtest chain is usually unique)

**Comment by juanky201271** [comment]
@AloeareV I'm going to add a warning/message to the user when is changing the server to another one with different chain... just after the user click `Save` en `Settings`...

If you change to another server with the same `chain`, the App keep going without any problem/warning... nothing.
