### ISSUE TITLE
Basic Mode

### ISSUE THREAD

**Issue by juanky201271** [zingolabs/zingo-mobile#394]
@zancas @AloeareV @Oscar-Pepper @fluidvanadium @Edicksonjga 

## Let's talk about `Basic Mode`...
* Basic Mode will be the Mode `by default`
## Installation: 
When the user install the App, directly it is going to go to `receive` with only the UA. When the wallet is new, with no balance & no transactions... the only thing the user can do is: give someone the UA to receive funds...
## Drawer Menu: 
* About
* Settings (only mode, privacy, currency & language)
* Wallet Seed (only if the wallet have funds or transactions)
* Financial Insight (only if the wallet have transactions)
## Tabs:
* History - I think the user needs to see the transaction list (only if the wallet have txs)
* Send - I think the user needs to use this screen. (only if the user have some funds)
* Receive - Here we put only the UA, no Z and no T.
## Settings:
* Mode: Basic / Advance.
* Privacy: High / Normal
* Language: English / Spanish.
* Currency: No currency / US Dollars.

These are the main ideas in my head. Please let me know your opinions about everything...

**Comment by Edicksonjga** [comment]
Where will 'Restore' be in basic mode (default mode)?

**Comment by juanky201271** [comment]
> Where will 'Restore' be in basic mode (default mode)?

Good point, if the user wants to open a different wallet because the user have a `seed`... Maybe we need the Drawer Menu option: `Change to another wallet` with only two buttons in the first screen: `New` & `Restore`... How about this?

**Comment by Edicksonjga** [comment]
> > Where will 'Restore' be in basic mode (default mode)?
> 
> Good point, if the user wants to open a different wallet because the user have a `seed`... Maybe we need the Drawer Menu option: `Change to another wallet` with only two buttons in the first screen: `New` & `Restore`... How about this?

The two essential functions for starting a wallet are **Create** and **Restore**, don't hide them.

This is how I see it:

**When installing:**

Welcome screen with some information, logo and 'Get started' button.

**When you tap on 'Get started':**

- Create new wallet.
- Import existing wallet (which import wallet supports Seeds and Viewing Keys in the same text entry).

On this screen you can add the three-dot menu for the other functions.

**Comment by juanky201271** [comment]
Another idea from @fluidvanadium ... is: The Restore screen could be only one, where you can read a QR or copy/paste one the two things... a `seed` or a `ufvk`... maybe this way is easier for `Aunt Grizelda`, I don't know.

**Comment by fluidvanadium** [comment]
instead of syncing screen, we could have a basic status animation like a blinking yellow triangle.

**Comment by fluidvanadium** [comment]
aunt grizelda doesnt need to worry about viewkey

**Comment by juanky201271** [comment]
> aunt grizelda doesnt need to worry about viewkey

yes, you're right... in basic mode only seed....

**Comment by juanky201271** [comment]
> instead of syncing screen, we could have a basic status animation like a blinking yellow triangle.

Good idea... syncing icons can be:
- gray square => means `stop`
- yellow blinking triangle => means `syncing`
- green check => means `fully synced`

And, of course, the sync report screen is too complicated for basic mode.

**Comment by Edicksonjga** [comment]
Do you mean that in basic mode the user will not be able to see his Viewing Key or that he will not be able to restore with a viewing key?

I hope it is the former and not the latter.

**Comment by juanky201271** [comment]
> Do you mean that in basic mode the user will not be able to see his Viewing Key or that he will not be able to restore with a viewing key?
> 
> I hope it is the former and not the latter.

Viewing key is too complicated for basic users... The idea would be if you want use VK you have to change the App to advance mode...

**Comment by Edicksonjga** [comment]
> > Do you mean that in basic mode the user will not be able to see his Viewing Key or that he will not be able to restore with a viewing key?
> > 
> > I hope it is the former and not the latter.
> 
> Viewing key is too complicated for basic users... The idea would be if you want use VK you have to change the App to advance mode...

Will it be possible to activate the Advanced Mode before starting any wallet?

**Comment by juanky201271** [comment]
> > > Do you mean that in basic mode the user will not be able to see his Viewing Key or that he will not be able to restore with a viewing key?
> > > I hope it is the former and not the latter.
> > 
> > 
> > Viewing key is too complicated for basic users... The idea would be if you want use VK you have to change the App to advance mode...
> 
> Will it be possible to activate the Advanced Mode before starting any wallet?

Nope, because the idea is: When you install the App automatically the App create a wallet & go directly to the receive screen. In this moment the user have an empty wallet, no need more info that the UA (QR), after that, when the user have some funds... the user can send, view txs, view the seed, etc...
