### ISSUE TITLE
The build infrastructure installs Rust..  but how?

### ISSUE THREAD

**Issue by zancas** [zingolabs/zingo-mobile#4]
This is the recommended technique.   We need to review the code in detail to determine whether or not it's a sane security policy.

https://www.rust-lang.org/tools/install

**Comment by dannasessha** [comment]
Leaving this here: https://forge.rust-lang.org/infra/other-installation-methods.html

I also saw (can't currently find) a security evaluation of the standard install method.

If there's a better way to do it, I'd like to use it, but I think standard method is fine for the time being.

**Comment by zancas** [comment]
I poked this a tiny bit..  there's simply a standard Rust workspace rooted in the `rust` directory.  Pretty straightforward.  I think we can close this.   The build infrastructure provides native bindings for that workspaces Rust to interface with Android and iOS.
