### ISSUE TITLE
Interface design suggestions

### ISSUE THREAD

**Issue by EnderArrieta88** [zingolabs/zingo-mobile#409]
Hi, guys!

I want to share here some suggestions that came to my mind about the interface design of the **Zingo app for Mobile.** 

Some little things that have to do with colors, sizes, alignments and re-ordering of some elements that I think would give a visual style a little more stylized and without so much noise to the app.

1. My first suggestion is to reorder the elements at the top of the application, as well as aligning everything that is balance, logo and buttons, even changing the size of the logo and aligning it with the rest of the elements. I think it is not necessary that the logo appears large and misaligned in all sections, since being inside the app, users will know that they are in Zingo, so it is not necessary that the logo is displayed too large in each section. This way it would look better.

2. In the **"Sync / Rescan Report"** section, I also sugges
making some adjustments to the size of the logo, leaving it aligned with the menu so that it is always homogeneous in all sections. And eliminating the "Close" button, as this would give the user much more space to visualize the synchronization process without the need to scroll. To return or exit the sections, you can touch the menu as you normally do today.

4. I also suggest a change in the colors of the app and thus offer a more modern visual appearance and less noise. Using softer and more subtle colors make the user experience more pleasant and make them want to stay in the app while performing their operations.

Here I will leave some images where I show you some changes I made in the design so you can visualize my suggestions.

I hope you like them.

![Zingo-00](https://github.com/zingolabs/zingo-mobile/assets/133868177/051ef90e-34ad-401c-a273-1c83dd8ca8fe)
![Zingo-02](https://github.com/zingolabs/zingo-mobile/assets/133868177/55a04b5e-a5fc-41c0-af5c-d67d3ff7866a)
![CHANGE COLORS](https://github.com/zingolabs/zingo-mobile/assets/133868177/8904bd3f-4777-4652-b4b1-6d5f7a9a36fd) 
![Zingo-00C1](https://github.com/zingolabs/zingo-mobile/assets/133868177/5603d1b1-b29c-4b55-8ee4-47b32c8547fd)
![Zingo-00C2](https://github.com/zingolabs/zingo-mobile/assets/133868177/f79a5372-d2bc-483a-a781-1fb12b8d32ff)

**Comment by juanky201271** [comment]
@EnderArrieta88 
First of all, thank you so much for taking the time and the effort for writing down this suggestions...

We will take all of them in consideration...

**Comment by juanky201271** [comment]
We decided to reduce the logo size (Header) in order to make the first `line` with:

- Burger menu
- read-only icon
- version
- mode
- Privacy toggle

You will see in the next release.

**Comment by juanky201271** [comment]
Since @edicksonja and Robmar are working in a new design I'm going to close this issue. @EnderArrieta88 you can contact with them, maybe some of your idea can be merge with the new design.
