### ISSUE TITLE
persistent menu

### ISSUE THREAD

**Issue by fluidvanadium** [zingolabs/zingo-mobile#413]
![Screenshot from 2023-06-19 09-03-32](https://github.com/zingolabs/zingo-mobile/assets/111296437/d82173b4-379c-4171-b42d-f058b0ee0a8b)

this menu should be accessible from each of the tabs

**Comment by fluidvanadium** [comment]
the history/send/receive screen should be on top of the menu. maybe it should be called the *transactions* tab

**Comment by juanky201271** [comment]
I think the standard behavior of the `drawer menu` is like that... when the menu overlay the screen, move it to the right... and cover the rest of the screen with a layer that you only can tap anywhere for closing the menu...

**Comment by juanky201271** [comment]
Closing because the above reason.
