### ISSUE TITLE
server menu consistency

### ISSUE THREAD

**Issue by fluidvanadium** [zingolabs/zingo-mobile#414]
these menus need to look the same.

under the "server" tab, not settings

![Screenshot from 2023-06-19 09-29-01](https://github.com/zingolabs/zingo-mobile/assets/111296437/ee1aaa6f-3b22-462c-99cb-40e52bb6ecc5)

![Screenshot from 2023-06-19 09-25-15](https://github.com/zingolabs/zingo-mobile/assets/111296437/5cc16c1c-8ca1-489c-b3fb-4b760377aafb)

**Comment by fluidvanadium** [comment]
the new widget is really pretty

**Comment by fluidvanadium** [comment]
can we also make a test-id and an example test that connects to testnet without first making a mainnet wallet?

**Comment by juanky201271** [comment]
Yes, I can do that. But if you start with a clean emulator, you can first change the server & after you can create a new wallet in the new server... I mean, you don't need to create a mainnet wallet first.

**Comment by juanky201271** [comment]
> these menus need to look the same.
> 
> under the "server" tab, not settings
> 
> ![Screenshot from 2023-06-19 09-29-01](https://user-images.githubusercontent.com/111296437/246787804-ee1aaa6f-3b22-462c-99cb-40e52bb6ecc5.png)
> 
> ![Screenshot from 2023-06-19 09-25-15](https://user-images.githubusercontent.com/111296437/246787184-5cc16c1c-8ca1-489c-b3fb-4b760377aafb.png)

Yesssssss, I need to unify the chain_type selection with the new widget... I'll do ASAP.

**Comment by fluidvanadium** [comment]
![Screenshot from 2023-06-30 02-30-40](https://github.com/zingolabs/zingo-mobile/assets/111296437/b21afb13-35b1-460b-a83e-af86f1611c19)

beautiful.
