### ISSUE TITLE
Add new Global lightwalletd servers from Nighthawk

### ISSUE THREAD

**Issue by luckytokidoki** [zingolabs/zingo-mobile#419]
I think we should add these to the server list options:

Location | Host | Port
-- | -- | --
North America | na.lightwalletd.com | 443
South America | sa.lightwalletd.com | 443
Europe & Africa | eu.lightwalletd.com | 443
Asia & Oceania | ai.lightwalletd.com | 443

Source: https://forum.zcashcommunity.com/t/nighthawk-apps-launches-global-zcash-light-client-infrastructure/44768/10

**Comment by luckytokidoki** [comment]
These endpoints likely don't support the transaction size filter.

**Comment by juanky201271** [comment]
Thanks @luckytokidoki those are very interesting alternatives...

**Comment by juanky201271** [comment]
@zancas What do you think about this? We are using already `mainnet.lightwallted.com` as a primary server, make any sense to include those new server in that list? or maybe detect the country of the device and use one or another?

**Comment by vamsiikrishna** [comment]
![ping_test](https://github.com/zingolabs/zingo-mobile/assets/554887/a29184f2-049c-4d40-982e-24f0b833f83c)

Picking the right server can make a big difference while the users are syncing. 

https://main--dreamy-pithivier-3c39d0.netlify.app/

**Comment by zancas** [comment]
I think that the user should have the option to select a server, but should never be forced to make a decision about something they don't understand.

**Comment by juanky201271** [comment]
Maybe for advance users we can put a toggle to select the Zone of the mainnet.lightwallted.com... and the expert user can choose: ai, eu, na or sa... (or the normal one: mainnet), just an idea...

**Comment by juanky201271** [comment]
Let's reactivate this since the two principal server are down in this moment...
@zancas @Edicksonjga 
Maybe we need to add another way to set the server: `Automatic`, What do you think? and add to the list at least another one like: `https://na.lightwalletd.com:443`.

**Comment by Edicksonjga** [comment]
> Let's reactivate this since the two principal server are down in this moment...
> @zancas @Edicksonjga 
> Maybe we need to add another way to set the server: `Automatic`, What do you think? and add to the list at least another one like: `https://na.lightwalletd.com:443`.

Yes, new servers need to be added, not just 1 of the Nighthawk Global Servers, I consider it best to add all of them and add the Automatic option so that the wallet changes servers depending on the ping or depending on which server is most up to date with the blockchain.

Maybe this way Setting > Server:

- Auto
- Custom

And in the text entry when selecting the Custom option add a button to display the list of servers, so the user can select from the list or paste the URL of any other that is not in the default list.

**Comment by juanky201271** [comment]
we included the new servers in the last release: https://github.com/zingolabs/zingo-pc/releases/tag/zingo-pc-1.0.4
