### ISSUE TITLE
testnet server can supply mainnet

### ISSUE THREAD

**Issue by fluidvanadium** [zingolabs/zingo-mobile#430]
this looks weird right here. and i can load a mainnet seed while connected to testnet server...
![Screenshot from 2023-07-05 21-08-41](https://github.com/zingolabs/zingo-mobile/assets/111296437/e653aa85-a70f-4c99-9aec-dca96499aa34)

**Comment by juanky201271** [comment]
@fluidvanadium I feel the same, but I remember @zancas  explaining about the user have to be aware of the `chain type` and select explicitly...  This feature is only available in `expert` mode... and mix the chain with the server is a really real possibility... and I don't know if the results can be a disaster or not...

**Comment by juanky201271** [comment]
I think everybody is aware of this situation, the seeds can be used in different chains... closing this issue because IMO there is nothing to fix here.
