### ISSUE TITLE
Basic Mode - Synchronisation Percentage

### ISSUE THREAD

**Issue by Edicksonjga** [zingolabs/zingo-mobile#438]
I have been using Zingo's Basic Mode and there is no way to access the Synchronisation Report, that's fine, being a basic mode you don't need all that information shown in that section.

**What is necessary?**

The synchronisation percentage, have it reflected in the interface so the user knows how much has been synchronised and how much is missing.

**How to do that?**

1. Through a text with the amount ranging from 0 to 100%.
2. Add a loading animation, it can be a horizontal bar or a circle, [example](https://www.freepik.es/vector-premium/conjunto-coleccion-barras-carga-progreso-circulo_7287955.htm).
3. Take advantage of the existing animation and make the synchronisation progress visible through the animation.

![Screenshot_20230711-163233.jpg](https://github.com/zingolabs/zingo-mobile/assets/37910384/fea63693-1b73-44f8-8e72-09ec3388f7be)

**Why is this necessary?**

**Synchronisation in Zcash is not the fastest**, regardless of the synchronisation protocol/method used, synchronisation takes time because data has to be downloaded, decrypted and processed which results in a rather long waiting time if the user does not synchronise regularly, has slow internet or his device is not that powerful.

Because of the above I think it is necessary to know what you have synchronised and what is still to be synchronised while keeping the basic mode as no advanced information is provided.

**Comment by juanky201271** [comment]
@Edicksonjga Thanks for the idea... @zancas had a lot of experience with new users, what do you think about two possible scenarios:
* Change the `play` icon color -> create 10 different tones between yellow and green and change the tone every 10% in the sync progress... less aggressive, less info to the basic user.
* The same but including somehow the % inside or outside the icon...

**Comment by zancas** [comment]
We're still thinking about this.

**Comment by Oscar-Pepper** [comment]
maybe we could display a percentage of [no. of blocks synced in current sync / no. of blocks not yet synced at start of sync]
i think this is easy to understand whats happening for a basic user but also doesnt suffer from blockchain scaling issues of showing percentage of blockchain synced.

one downside is it doesnt show how far behind the blockchain the wallet is, maybe we could use @juanky201271 idea of colouring the `play` icon so it becomes more red as the number of unsynced blocks gets higher? can we explain this easily or is this obvious?

**Comment by juanky201271** [comment]
Thank you everyone... I will try to make everybody happy with this... let's see...
