### ISSUE TITLE
Bugs and suggestions for tooltips

### ISSUE THREAD

**Issue by Edicksonjga** [zingolabs/zingo-mobile#440]
The change from toast to tooltips is simply spectacular, they have a better design, improve the user experience, they are more functional since animations or buttons can be added to them and they can be used as guides to offer information to users.

**Bugs:**

1. When you copy two different types of information that generate two types of tooltips, both tooltips should be displayed, that doesn't happen, the previous tooltips are always displayed as tooltips of the next copied information, see the video.

https://github.com/zingolabs/zingo-mobile/assets/37910384/ade5892e-0bff-43be-97e6-b18b00fb5574

2. Some texts are not fully displayed in the tooltips, adding more characters/display space could be a solution, or you can also optimize the texts to express the same thing with fewer words, see image.

![Screenshot_20230712-073911.jpg](https://github.com/zingolabs/zingo-mobile/assets/37910384/9754e743-b2e8-4ab1-836c-cb2dd3c4a55d)

**Suggestion:**

1.

It's better to use tooltips (or maybe popups or a dropdown - not sure what the correct term is for the latter) to confirm actions.

Visually it is not cool to fill a button with text, a timer and change the color of the button to confirm an action, this can lead to confusion for users by having a button that changes every time it is touched.

It is better to use other methods where the information can be better appreciated and so the user can safely decide what to do.

![Screenshot_20230712-072641.jpg](https://github.com/zingolabs/zingo-mobile/assets/37910384/9da752f2-6791-4764-8a76-73bf778bbaf3)

![Screenshot_20230712-111728.jpg](https://github.com/zingolabs/zingo-mobile/assets/37910384/ea517658-0c3a-4327-852b-dbacb93b2a65)

![Screenshot_20230712-111732.jpg](https://github.com/zingolabs/zingo-mobile/assets/37910384/cea433a1-5e2d-4db6-acf5-8f853dce119c)

2.

When copying information, make the following tooltips hide the previous one, see video.

If the tooltips are different than above, you can choose to immediately hide one and hide the other, show the two on top of each other, overlap the two one behind the other, waiting for one to disappear and then over time the other to disappear.

https://github.com/zingolabs/zingo-mobile/assets/37910384/1febb3d3-7c26-47b4-8c85-373aa4fd349b

**Comment by juanky201271** [comment]
Thanks @Edicksonjga 

Bugs:
1. I'm going to look into this...
2. I need to put three lines for the tool-tips, and let's see if it is enough.

Suggestions:
1. We use the color `red` for a few things, actions that can be dangerous to the user... We will take your suggestion in consideration, for sure.
2. For now the idea is: to fill a queue of messages/tooltips with no repetitions, and to show each one for 4 seconds... I think here can be a good idea to show different kind of messages with different duration, short messages 2 seconds, and complex ones 4 seconds.

@zancas What do you think about the `red` buttons (prices, etc...)?

**Comment by Edicksonjga** [comment]
> ...What do you think about the red buttons (prices, etc...)?

The problem is not the color, you can use red buttons taking my suggestion to use popup windows, dropdown sheets or tooltips for action confirmations.

What I think should not be done is to use the same button, that is, Action - Information - Warning - Confirmation.

Example...
![IMG_20230713_065942_133.jpg](https://github.com/zingolabs/zingo-mobile/assets/37910384/c9247274-ab3b-4ae1-a916-6bb9e6ba3978)

If I'm not mistaken, we already have reports of users who don't know where to touch, perhaps because they find it confusing to have to touch the same button so many times.

**Comment by Edicksonjga** [comment]
Thanks @juanky201271 🛡️

**Comment by juanky201271** [comment]
@Edicksonjga Let's do this easier to basic users... when a user in basic mode ask for fetching the price, only have to click 1 time, no `red` button for confirmation... The experts can handle the `red` button. Let's think this for expert mode later... Our priority is `basic mode`.

**Comment by Edicksonjga** [comment]
I'll close this, the recently implemented in beta works fine. @juanky201271 👍
