### ISSUE TITLE
BUG - New wallet when switching to Basic Mode

### ISSUE THREAD

**Issue by Edicksonjga** [zingolabs/zingo-mobile#441]
Sometimes the app will generate a new wallet by switching to Basic Mode when you try to Open another wallet.

**Steps:**

1. Tap on Open another wallet and confirm the action
2. Being on the Home screen, tap on the three-dot menu and then on Switch to Basic mode
3. The app displays an error and prompts the user to Switch Server and Open Active Wallet
4. Tapping on that button generates a new wallet (most of the time) and doesn't open the active wallet as indicated by the button

**Demo:**
https://github.com/zingolabs/zingo-mobile/assets/37910384/3e6ca5d2-2590-4739-a3fb-98fdc30122c0

I don't know why the error is thrown when switching to Basic Mode, but I'll be on the lookout for further testing based on feedback or suggestions.

**Comment by juanky201271** [comment]
Upssssssss, really good catch. I will fix it ASAP. Thanks @Edicksonjga

**Comment by Edicksonjga** [comment]
> Upssssssss, really good catch. I will fix it ASAP. Thanks @Edicksonjga 

I have tested in the latest beta and the error persists.

The error appears and quickly automatically opens the old wallet or a new wallet (most of the time the latter). @juanky201271

**Comment by juanky201271** [comment]
@Edicksonjga did you see this error in the new release?

**Comment by Edicksonjga** [comment]
> @Edicksonjga did you see this error in the new release?

No, the new release no longer has the option to switch to Basic Mode after using the Open Another Wallet option. @juanky201271

**Comment by juanky201271** [comment]
closing...
