### ISSUE TITLE
feature request - if the wallet has no funds in it and im just trying to access expert mode, dont give such a hard time about not saving the seed

### ISSUE THREAD

**Issue by fluidvanadium** [zingolabs/zingo-mobile#443]

**Comment by juanky201271** [comment]
I'm not sure if I understand this... If you open the App in `basic` mode there is no mention to the seed at all... in this case you can go to settings and change it to `expert` mode easily...

**Comment by juanky201271** [comment]
@fluidvanadium some new idea about this?
