### ISSUE TITLE
View Seed / VK & Create Transactions Addicional Security

### ISSUE THREAD

**Issue by juanky201271** [zingolabs/zingo-mobile#446]
Several user suggested additional security check when you access to the Seed/VK or when you send some funds.
I think the best option here is to use the security of the device before the user do these actions.

**Comment by Edicksonjga** [comment]
Sounds like a good choice to me, some Wallets offer an internal pin and don't use system security, but using system security also ensures that you won't be screen recorded while typing the pin, password, etc.

**Comment by juanky201271** [comment]
I added PIN/Touch/Face based security to several screen and actions.
