### ISSUE TITLE
BUG - QRs from payment URIs are not processed

### ISSUE THREAD

**Issue by Edicksonjga** [zingolabs/zingo-mobile#454]
The wallet does not process information from QR codes that contain more parameters than just an address.

**Steps:**

1. Enter Send
2. Touch the button to Scan QR codes
3. Scan QR code with more parameters than just an address

https://github.com/zingolabs/zingo-mobile/assets/37910384/47d0d930-ac10-4f3a-806c-07b294c846e6

**Expected behavior:**

The wallet must process the information by filling in the fields of all the parameters specified in the payment URI.

**How it's working:**

The wallet processes QR codes that only contain the Zcash address parameter, if the URI contains other parameters the wallet throws an error.

Techno Phantom X
Android 11
Zingo Beta 1.2.4 (125)

**NOTA 1:** tap on the payment URI if it works, the problem is with scanning.

**NOTE 2:** This also affects the stable version, [see here](https://twitter.com/naomibrockwell/status/1681116453850996736).

**URIs (video):**

**Zecpages:**

![Screenshot_20230719-082154.jpg](https://github.com/zingolabs/zingo-mobile/assets/37910384/e6a1626d-2f73-4b00-91b9-cc4a12219a75)

zcash:zs1j29m7zdhhyy2eqrz89l4zhk0angqjh368gqkj2vgdyqmeuultteny36n3qsm47zn8du5sw3ts7f?amount=0.001&memo=VGV4dCBkZSB0ZXN0

**GrapheneOS:**

![Screenshot_20230719-082314.jpg](https://github.com/zingolabs/zingo-mobile/assets/37910384/9caef645-17a8-4da5-82ce-797e2f05502c)

zcash:t1SJABjX8rqgzqgrzLW5dUw7ikSDZ2snD8A?label=GrapheneOS%20Foundation&message=Donation%20to%20GrapheneOS%20Foundation

**Free2Z:**

![Screenshot_20230719-082607.jpg](https://github.com/zingolabs/zingo-mobile/assets/37910384/a552cb2e-4e4d-46f4-a5d4-78fff92f0520)

zcash:u1470pl08vve6y9xmpr3veffldc9mec4z3yqag5exrpjxm7vg5u5jtn2g4v8aqhn8yagckm67639vdhajh0qyp5zt4mkt4lgf63mf8rzx7l3ezwvtppzxywefzvmdj96xxylj57lskpgp4jflk6h3rl92yqevlht8hg8d0d37zaxlamgxp8rgadd6dr3gkffzt5klm2unmy2wnc35js2f?amount=0.500&memo=

**Comment by juanky201271** [comment]
@Edicksonjga can you provide the URI or URI's with those Qr codes? or same screenshots? Thanks for the issue.

**Comment by Edicksonjga** [comment]
> @Edicksonjga can you provide the URI or URI's with those Qr codes? or same screenshots? Thanks for the issue.

Issue edit. @juanky201271

**Comment by juanky201271** [comment]
Gracias.
