### ISSUE TITLE
Error in Shield button when changing from expert to basic mode and vice versa.

### ISSUE THREAD

**Issue by Edicksonjga** [zingolabs/zingo-mobile#460]
Having only funds in the transparent pool, the button says *Shield Transparent funds* in expert mode, but:

1. Switch to **Basic Mode**
2. Button changes to **Shield all funds**
3. Return to expert mode
4. The button stays on Shield all funds and shows the **pool selector**
5. Restart the app to return to the state **Shield transparent funds**

https://github.com/zingolabs/zingo-mobile/assets/37910384/6d91e049-26c0-436e-97cc-7c9c0b4d0452

Tecno Phantom X
Android 11
Zingo Beta 1.2.4 (125)

**Comment by juanky201271** [comment]
I just test it in `dev` & it's working fine, I remember that I fixed this issue a few days ago... I need to send you a new APK...
@Edicksonjga Thanks so much.

**Comment by Edicksonjga** [comment]
> I just test it in `dev` & it's working fine, I remember that I fixed this issue a few days ago... I need to send you a new APK...
> @Edicksonjga Thanks so much.

I have carried out tests in the last beta and yes, it is already fixed.
