### ISSUE TITLE
Basic Mode: When the wallet receive funds the first time

### ISSUE THREAD

**Issue by juanky201271** [zingolabs/zingo-mobile#477]
If the wallet have no funds and have no transactions the user can't see the seed, make sense because only with funds or transactions the user have something to save.

But when the user receive funds I think could be a good idea to interrupt to the user with the `seed` screen because otherwise the user could lost the funds because the App doesn't give him/her the opportunity to save the seed phrase and birthday. The user actually have the option in the side menu, but maybe the user don't know anything about it.

**Comment by zancas** [comment]
I am in favor..   100%.

We want to focus the *newest* users on the *first* step into the community.   To join the zcash community, the *must* receive zcash.

As *soon* as they have funds, they need to take the next step, backing up their seed.

**Comment by juanky201271** [comment]
> I am in favor.. 100%.
> 
> We want to focus the _newest_ users on the _first_ step into the community. To join the zcash community, the _must_ receive zcash.

I agree 100%, nobody in the community AFAIK is focus in to enroll new users, and this is an important task. IMO.
