### ISSUE TITLE
Wrong fee with command `list` and `summaries`

### ISSUE THREAD

**Issue by juanky201271** [zingolabs/zingo-mobile#507]
I'm using an old wallet, birthday: 1398510
seed: `nerve shrimp grunt thunder error vocal choice glass love decline target couple peasant section kite derive need nation lunar excuse strategy beauty manual soap`
zingolib: mob-release-1.2.5_126-243-g408826c5

This is an old tx, the real fee was: 0.00001

https://zcashblockexplorer.com/transactions/1b173590bc22e6a03c66aa571ae2be2a66f17db06e850c88ad015cffee574b9d

{
"address": "u1e6ysxkvwwc0d2skl65rl62xa0w8el66tp9pt98w7n8lpvxrwenleyt82ep24llm9uphqrukn0v5ff3z9dx8u7k7ev73h5s4h8hverf8ndfp6m2akc6tq72dcuz6updf3cdh7l2g3gl64q36v786cxa8kd06y4jyp4axkyjfpcjvsshp730szcly87pwe3nccdkh9genqaec6s920adq", 
"amount": 10864316, 
"block_height": 1714688, 
"datetime": 1656099584, 
"memo": "null, null", 

"outgoing_metadata": [{
"address": "zs16lp2my3pmeu2uujsk5hjskptds33kgur5yuykqldvwr9e2xlfhant3a5mdujtqfpzlumynf3xe8", 
"memo": null, 
"value": 1110}], 

"position": 0, 
"txid": "1b173590bc22e6a03c66aa571ae2be2a66f17db06e850c88ad015cffee574b9d", 
"unconfirmed": false, 
"zec_price": null
}

![Screenshot_1693960714](https://github.com/zingolabs/zingo-mobile/assets/43755989/cb453b6a-6cae-4720-bdd9-239abebcbd05)

**Comment by AloeareV** [comment]
The "null, null" seems to imply that we receive two notes in this transaction, neither of which are change. There's also an outgoing_metadata to a sapling address that seems to be external....and the block explorer says there are only two outputs in the transaction, so something has to be being accounted for twice. I suspect the fact that this is an old spend (from back when change notes were created differently) is confusing something. 

When I run `summaries`, I get 
  {
    "amount": 18446744073709550506,
    "block_height": 1714688,
    "datetime": 1656099584,
    "kind": "Fee",
    "memos": [],
    "pool": "",
    "price": null,
    "txid": "1b173590bc22e6a03c66aa571ae2be2a66f17db06e850c88ad015cffee574b9d"
  }
  This amout looks like integer underflow...it's usize::MAX - 2048. I don't know where 2048 could be coming from, though, as it's not the fee that was paid...

**Comment by zancas** [comment]
Hi @fluidvanadium this looks like a `summaries`-related bug..  can we test it in `integration_tests.rs`?

**Comment by juanky201271** [comment]
The bug is still there... v: mob-prerelease-1.3.0-95-g95b8a2d5

![image](https://github.com/zingolabs/zingo-mobile/assets/43755989/b2182d35-80f7-4372-8a27-7c194e3d5d44)

**Comment by juanky201271** [comment]
same problem with the same seed & tx... 
![Screenshot_1697072851](https://github.com/zingolabs/zingo-mobile/assets/43755989/de14464c-8a9c-433e-b8f6-71156d221125)
![Screenshot_1697072867](https://github.com/zingolabs/zingo-mobile/assets/43755989/fb8f5546-5a9d-4944-8618-61337b72484d)

**Comment by juanky201271** [comment]
> The "null, null" seems to imply that we receive two notes in this transaction, neither of which are change. There's also an outgoing_metadata to a sapling address that seems to be external....and the block explorer says there are only two outputs in the transaction, so something has to be being accounted for twice. I suspect the fact that this is an old spend (from back when change notes were created differently) is confusing something.
> 
> When I run `summaries`, I get { "amount": 18446744073709550506, "block_height": 1714688, "datetime": 1656099584, "kind": "Fee", "memos": [], "pool": "", "price": null, "txid": "1b173590bc22e6a03c66aa571ae2be2a66f17db06e850c88ad015cffee574b9d" } This amout looks like integer underflow...it's usize::MAX - 2048. I don't know where 2048 could be coming from, though, as it's not the fee that was paid...

At least this tx have a correct fee...
{
    "amount": 1110,
    "block_height": 1714688,
    "datetime": 1656099584,
    "kind": "Sent",
    "memos": [],
    "pool": "",
    "price": null,
    "txid": "1b173590bc22e6a03c66aa571ae2be2a66f17db06e850c88ad015cffee574b9d",
    "to_address": "zs16lp2my3pmeu2uujsk5hjskptds33kgur5yuykqldvwr9e2xlfhant3a5mdujtqfpzlumynf3xe8"
  },
  {
    "amount": 1000,
    "block_height": 1714688,
    "datetime": 1656099584,
    "kind": "Fee",
    "memos": [],
    "pool": "",
    "price": null,
    "txid": "1b173590bc22e6a03c66aa571ae2be2a66f17db06e850c88ad015cffee574b9d"
  },

version
mob-prerelease-1.3.0-135-g53cffa3b

**Comment by juanky201271** [comment]
In the last testings I didn't see this problem, closing...
