### ISSUE TITLE
Issue with server connection

### ISSUE THREAD

**Issue by lexihel** [zingolabs/zingo-mobile#533]
Hello team! there seems to be an issue connecting to the server when Zingo! for Android is working in the background or network connection is unstable, where the balances are different each time sync'ing process is finished.

**First try:** 
1.- I restored a wallet with some balance in it and started the sync'ing process.
2.- Left Zingo! running in the background while alternating between my browser, a Telegram chat and back to Zingo! (I disabled smart battery managment to prevent Android from closing the process).
3.- After sync was complete, I checked the balance. There were some funds in Sapling pool that shouldn't be there.

![1](https://github.com/zingolabs/zingo-mobile/assets/9355622/e9824318-57f5-4169-9c4d-84b4ce3c122e)
![2](https://github.com/zingolabs/zingo-mobile/assets/9355622/2a0818da-32f5-477d-896e-f3aba7a4de57)
![3](https://github.com/zingolabs/zingo-mobile/assets/9355622/84ae0157-e370-4d9f-848b-97a086a11509)
![4](https://github.com/zingolabs/zingo-mobile/assets/9355622/89e2e7a5-8ee0-42d3-b9fc-1711ec81e00d)

**Second Try (no screen capture, sorry):**
1.- I ordered Zingo! to re-scan, to start all over.
2.- Left it, again, running in the background.
3.- Zingo! app told me syncronization was complete, but it was too soon. The balance in the wallet was from really old transactions. New notes were not scanned/detected

**Third Try**
1.- Started a new re-scan process
2.-Left Zingo! Wallet running, screen on, no multitasking, with the Syncronization Information Screen open.
3.- When the process was finished, I checked the balance. It was the expected amount, no funds in sappling, only a few in Orchard.

![5](https://github.com/zingolabs/zingo-mobile/assets/9355622/9ca316ce-49e3-4079-8547-3c97e38a194d)
![6](https://github.com/zingolabs/zingo-mobile/assets/9355622/7e45d982-8efb-4a06-8375-c1d25f5d0f26)

I'm using Zingo! Mobile Beta version, provided by Edicksonjga, on an Android devices, Arm64 V8 running Android 12, with 8GB RAM.

**Comment by juanky201271** [comment]
Thanks @lexihel for all your tests. This is really helpful.

I can see something really interesting in the screenshots... @AloeareV @zancas  please take a look at txid: `c874afb...`:
- First test (wrong) in this tx you can the fee with a ridiculous value... (we notices this before...)
- Third test (correct) in the same tx you can see the correct fee.

The question is: How is possible this behavior with the same device, version, server, etc... the only different things are:
- syncing in background, first time someone test this with the new syncing process.
- intermittent internet connection. 

The pattern that is clearly repeated in both situations is: the synchronization process stops (internet or background) and then resumes again (internet returns or the background process is launched)... in these two cases something zingolib does that does not convey the blockchain information correctly.

**Comment by lexihel** [comment]
I'm glad I could help! Hope it's enough for you guys to solve the problem. If you need anything else, let me know.

**Comment by juanky201271** [comment]
@lexihel I don't know if you could do the same testing with zingo-pc???? maybe @edicksonjga can help you... We want to know if this happen there as well... thanks in advance.

**Comment by juanky201271** [comment]
@edicksonjga This issue is still in your last testings...?????

**Comment by Edicksonjga** [comment]
> @edicksonjga This issue is still in your last testings...?????

@juanky201271 In the last beta you passed me it still crashes, if you have another one you can try again.

**Comment by juanky201271** [comment]
In the last release, Android 1.3.0, this is fixed, closing... If you @lexihel or @Edicksonjga have any problem feel free to re-open the issue. Closing...
