### ISSUE TITLE
Provide option for 12 word seed

### ISSUE THREAD

**Issue by metalworker2** [zingolabs/zingo-mobile#549]
Zingo makes users backup a 24 word seed. This is a lot of words, tedious to write down and back up, for example using steel back ups. 12 words are easier to back up and equal in security to the private keys generated by the seed. As [Adam Back says](https://twitter.com/adam3us/status/1635218357493563392), "12 words is enough."

Longer explanation:

https://foundationdevices.com/2023/06/make-12-words-the-standard/

**Comment by juanky201271** [comment]
Thanks so much @metalworker2 ...
@zancas What do you think about this?

**Comment by juanky201271** [comment]
I don't see any real improvement if we allow to use these kind of seed phrases... closing...

**Comment by metalworker2** [comment]
@juanky201271 you don't see users having to write down, backup on metal, enter into the app upon recovery, only half the amount of words as being a real improvement?
