### ISSUE TITLE
Make the _default_ setting maximally private

### ISSUE THREAD

**Issue by zancas** [zingolabs/zingo-mobile#55]
This may already be accomplished (apologies in advance if so), but I agree with this user:

https://github.com/zecwalletco/zecwallet-mobile/issues/71#issuecomment-1121566786

**Comment by juanky201271** [comment]
@zancas Yes, this problem is already fixed in this repo... Now you can change this toggle anytime in Android & IOS. Tomorrow I'll test it and I'll upload here some snapshots.

**Comment by zancas** [comment]
Great thanks!   I just wanted to confirm that the default is either `None` or `All` either of which is interesting.

Maybe we should talk about whether the default should be `None` or `All`?

**Comment by juanky201271** [comment]
Nope, the default value when you create a new wallet is: 'wallet'.

export class WalletSettings {
  download_memos: string;

  constructor() {
    this.download_memos = '**wallet**';
  }
}

What value do you prefer for default?

**Comment by zancas** [comment]
I vote for `none` as the default.

**Comment by juanky201271** [comment]
I change the default value to 'none'.

**Comment by zancas** [comment]
That fixes this issue.
