### ISSUE TITLE
Spanish traductions sometimes too long

### ISSUE THREAD

**Issue by juanky201271** [zingolabs/zingo-mobile#613]
We need to review al the Spanish Texts (buttons, titles, labels...) and make them in some cases shorter. 
I assign this to you, @edicksonjga because I remember this was your idea. (well I cannot assign it to you... actually)

**Comment by Edicksonjga** [comment]
Okay, I suggest uploading the strings to Crowdin, it is a good platform to translate and improve the application texts in different languages. @juanky201271

**Comment by juanky201271** [comment]
I sent you an invitation... this is the project: https://crowdin.com/project/zingo-mobile

**Comment by juanky201271** [comment]
I think we are done with this, for now... closing.
