### ISSUE TITLE
"zingo mobile is locked"

### ISSUE THREAD

**Issue by fluidvanadium** [zingolabs/zingo-mobile#618]
i cannot open latest zingo!mobile

https://github.com/zingolabs/zingo-mobile/assets/111296437/cb676150-a93c-40c3-b809-03c72a7102f9

**Comment by juanky201271** [comment]
Thanks, I can reproduce the problem in my Android device. Nice catch @fluidvanadium .

**Comment by juanky201271** [comment]
tested & fixed.
