### ISSUE TITLE
BUILD FAILED - com.android.builder.testing.api.DeviceException: No connected devices!

### ISSUE THREAD

**Issue by sebastianlujan** [zingolabs/zingo-mobile#690]
### BUILD FAILED: Deprecated Gradle features were used in this build

I am experiencing an issue while trying to launch Zingo Mobile after a successful build on my Arch Linux system. The build process completes successfully, but I am unsure of the next steps required to launch the application. Below are the details of my environment and the steps I have taken.

**Environment:**

**Operating System:** Arch Linux
`uname -a: Linux sebashack 6.10.7-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 29 Aug 2024 16:48:57 +0000 x86_64 GNU/Linux`

**Android SDK:**
`ANDROID_HOME: ${HOME}/Android/Sdk`|

bashrc and bash_profile configurations are set as follows:

**bash**
```
export ANDROID_HOME="${HOME}/Android/Sdk"
export PATH="${PATH}:${ANDROID_HOME}"
export PATH="${PATH}:${ANDROID_HOME}/build-tools"
export PATH="${PATH}:${ANDROID_HOME}/platform-tools"
export PATH="${PATH}:${ANDROID_HOME}/cmdline-tools/latest/bin"
export PATH="${PATH}:${ANDROID_HOME}/emulator"
```

Environment:

```
OS: Arch Linux 6.10.7-arch1-1
Gradle Version: 8.2
Rust Version: rustc 1.83.0-nightly (bd53aa3bf 2024-09-02)
Android SDK Version: Api 30
Docker Version: Docker version 27.2.0, build 3ab4256958
```

> Current Behavior:

The build completes successfully, but I am unable to launch the zingo-mobile application.
The application does not appear to start, and there are no clear error messages indicating the issue.
Expected Behavior:

The application should launch successfully after a successful build and installation.
Additional Information:

I have installed and configured Docker and Android SDK tools according to the project's requirements.
I have tried various commands to start the application, including ./gradlew commands and yarn start.

My error when i did yarn start:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:installDebug'.
> com.android.builder.testing.api.DeviceException: No connected devices!

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 1m 7s
```

How to proceed ?

**Comment by sebastianlujan** [comment]
To add more info, this is an extract of the error 

```
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
    Finished release profile [optimized] target(s) in 0.96s
     Running target/release/uniffi-bindgen generate ../rust/lib/src/zingo.udl --language kotlin --out-dir /home/sebas/zingo/zingo-mobile/zingo-mobile/android/app/build/generated/source/uniffi/debug/java

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:installDebug'.
> com.android.builder.testing.api.DeviceException: No connected devices!

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 1m 7s
info Run CLI with --verbose flag for more details.
Done in 96.09s.
```

**Comment by juanky201271** [comment]
You can try with this in a Terminal:
- `adb devices` (usually you get this name for the emulator: `emulator-5554`)
- `adb -s emulator-5554 reverse tcp:8081 tcp:8081`
- `yarn start`

@sebastianlujan

**Comment by sebastianlujan** [comment]
The problem was the flatpack android instalation, also the docs are outdated, to fix it , i install the android studio and set up it from the tar file, I'm working in a Dockerfile with a plug and play solution for Arch.
