### ISSUE TITLE
Revisit implications of referencing a tag instead of an explicit commit hash in zingolib

### ISSUE THREAD

**Issue by zancas** [zingolabs/zingo-mobile#70]

**Comment by juanky201271** [comment]
My knowledge about this is very small, but in my opinion It doesn't really matter, they are different ways to do the same.

**Comment by juanky201271** [comment]
A few months later, I think the implications are the same (zero AFAIK) ... maybe we can close this issue...

**Comment by juanky201271** [comment]
closing...
