### ISSUE TITLE
CI - We need to reduce the time of a few tasks

### ISSUE THREAD

**Issue by juanky201271** [zingolabs/zingo-mobile#703]
There are two task that we need to reduce the time consumption... :
- Pulling the regchest image -> https://github.com/zingolabs/zingo-mobile/actions/runs/10983031788/job/30492248896#step:14:1
- Android Building.

**Comment by juanky201271** [comment]
Probably the best thing to do is `reduce the size of the regchest image`... what do you think? @dorianvp @sebastianlujan

**Comment by juanky201271** [comment]
here, 55 minutes (no sense) -> https://github.com/zingolabs/zingo-mobile/actions/runs/10983818935/job/30493713056#step:14:1

**Comment by sebastianlujan** [comment]
It's possible, now is in the backlog to solve it ASAP.

**Comment by juanky201271** [comment]
The problem is in macos runners with docker, I changed the integration test to ubuntu and NO problem at all... I think we can close this issue...

**Comment by juanky201271** [comment]
I'm closing this issue because now we are using ubuntu runners and it's another world... fast enough.
