### ISSUE TITLE
Why did the Cargo.lock version of rand decrease?

### ISSUE THREAD

**Issue by zancas** [zingolabs/zingo-mobile#73]
https://github.com/zingolabs/zingo-mobile/pull/72#discussion_r904377642

**Comment by juanky201271** [comment]
I don't see the point of this issue honestly, I'm sure because of my lack of knowledge. I can see in the comment that the change of the `Cargo.lock` was because I did `cargo update` as I always do when I know that `zingolib` have new commits merged. I think we can safely close this issue.
