### ISSUE TITLE
Verify the verification? ✅❌

### ISSUE THREAD

**Issue by Edicksonjga** [zingolabs/zingo-mobile#738]
The wallet prompts for facial verification several times before proceeding with any action when you have the **Store wallet information on the device** option enabled.

**Steps:**

1. Go to Configuration from the menu
2. Enables the Store wallet retrieval information function on the device.
3. Open the App/Enter parameters/Change wallet/etc.

https://github.com/user-attachments/assets/87812c52-2150-46f2-9621-ffb0694efce8

Verification appears on almost any screen, the same is true for any type of security set on the device.

**Device:**

iPhone 15 Pro Max
iOS 18

**On Android this error does not occur, but having the feature enabled, authentication is required even if the checkboxes in the Use device security section are unchecked.**

**Comment by juanky201271** [comment]
Thanks man @Edicksonjga This is really weird indeed, I can't reproduce in my iPhone, but we need to fix this.

**Comment by juanky201271** [comment]
Yes, I can reproduce the problem when I enabled the new `Store wallet recovery Info`... working on it.
