### ISSUE TITLE
Bad performance switching between tabs

### ISSUE THREAD

**Issue by fluidvanadium** [zingolabs/zingo-mobile#741]
on Moto G, it takes about 1 second to switch between tabs

**Comment by fluidvanadium** [comment]
oh, probably related to https://github.com/zingolabs/zingolib/issues/1461

**Comment by juanky201271** [comment]
@fluidvanadium can you tell me the version of the App where you are experienced this?

**Comment by fluidvanadium** [comment]
![Screenshot_20241028-163047.png](https://github.com/user-attachments/assets/c046f4a3-8857-441d-a584-ee845e3c793b)

**Comment by juanky201271** [comment]
Hopefully today I'm going to upload a new Test version, and maybe you can try if this performance problem persist...

**Comment by juanky201271** [comment]
the new test release is available in Google Play 1.8.1 (198), please, can you test this issue against it. I hope the performance is better. @fluidvanadium

**Comment by fluidvanadium** [comment]
same issue

**Comment by juanky201271** [comment]
@fluidvanadium sorry, but I have to ask you again... what about 1.10.2?

**Comment by juanky201271** [comment]
I split the fetching of the data of the wallet and I removed some unused code about `notes`. I believe the performance is way better in Android. Closing for now, feel free to reopen again if you experience bad performance in the next  production version.
