### ISSUE TITLE
We are using a patched version of `bellman` crate

### ISSUE THREAD

**Issue by dannasessha** [zingolabs/zingo-mobile#83]
https://github.com/zingolabs/zingo-mobile/blob/dev/rust/Cargo.toml

We should evaluate this situation.

I think we should find a way in our own "home turf" logic to use the standard crate, or open the question to upstream, maybe even submit a PR.

**Comment by juanky201271** [comment]
What do you think about this issue? It's worthy to do some action about it...

**Comment by zancas** [comment]
Yes, we do want to upgrade away from any patches, if at all possible.

**Comment by juanky201271** [comment]
Bellman patch was removed yet. closing.
