### ISSUE TITLE
We are using an old version of `librustzcash`

### ISSUE THREAD

**Issue by dannasessha** [zingolabs/zingo-mobile#84]
I think we should try to update to the new version.

Solving this issue would also possibly solve #83

**Comment by AloeareV** [comment]
We're going to need to patch our version of librustzcash anyway, as orchard depends on very out-of-date librustzcash.

**Comment by juanky201271** [comment]
What do you think about this? make sense to do some action about this?

**Comment by juanky201271** [comment]
I think this is under control, now.... closing.
