### ISSUE TITLE
iOS app does not receive/display memo

### ISSUE THREAD

**Issue by skyl** [zingolabs/zingo-mobile#88]
I sent a tx with a memo to an iOS emulator running [979f309](https://github.com/zingolabs/zingo-mobile/commit/979f30944ed896cf1a97b660c89467c5e89623fc). The TX was received but no memo displayed in the TX detail. ZWL 1.7.13 does display the memo.

**Comment by juanky201271** [comment]
If you created a new wallet for this, the default value of `download_memos` is `none`. Issue: #55

**Comment by skyl** [comment]
> If you created a new wallet for this, the default value of `download_memos` is `none`. Issue: #55

so, there is no way to toggle this right now?

**Comment by juanky201271** [comment]
Yes, you can change this in settings anytime.

**Comment by skyl** [comment]
oh, OK, it's fine. Maybe optimal would be a little startup wizard with a little 45-second video explaining the options and making the user choose? Default private is OK though ... maybe a little link in the TX detail <no memos downloaded click here to download memos> or sth like that. Especially if people are used to the default in ZWL.
