### ISSUE TITLE
Remove diminished privilege user from build-pipeline

### ISSUE THREAD

**Issue by zancas** [zingolabs/zingo-mobile#89]
I don't anticipate this breaking the build from @juanky201271 's perspective, but since we don't have adequate CI to be sure, we'll need to wait until he can manually confirm.

See this comment:  https://github.com/zingolabs/zingo-mobile/pull/87#issuecomment-1175224147

**Comment by zancas** [comment]
To close this issue:

It's sufficient to manually verify the build against the merged commit on dev.

**Comment by juanky201271** [comment]
I can build from dev branch perfectly.
