### ISSUE TITLE
Allow users to specify what lightwalletd server to connect to, instead of hard-coding the server. 

### ISSUE THREAD

**Issue by AloeareV** [zingolabs/zingo-mobile#90]
It still probably makes sense to have a hardcoded default, and maybe even some other options also hard-coded in.

**Comment by juanky201271** [comment]
https://github.com/zingolabs/zingolib/pull/42
Good idea and we need to do it since in zingolib is done.

**Comment by juanky201271** [comment]
Would be nice to have a list of those servers, like:
* `https://zuul.free2z.cash:9067`

**Comment by juanky201271** [comment]
Now the users can choose between two servers... and they can specify a `custom` server too...
