### ISSUE TITLE
No memos help for newbs and people coming from ZWL

### ISSUE THREAD

**Issue by skyl** [zingolabs/zingo-mobile#93]
## What

Engage the user to choose their memo preference upfront when they start the wallet (maybe with short video explainer) AND/OR have a little link to settings <where's my memo?> in the transaction detail if the user has _no memo download_ configured (the default now)

## Why

It's confusing for new users and even more so for people who are used to ZWL to not have memos by default

## Ref

#88

**Comment by juanky201271** [comment]
I think would be good to put some `legend` when a new wallet is created...

**Comment by juanky201271** [comment]
We change the default value to 'wallet', I were right, the users are really confusing about what is happening with the memos... Thanks for the tip.
