### ISSUE TITLE
Figure out patching

### ISSUE THREAD

**Issue by AloeareV** [zingolabs/zingo-mobile#95]
We're using patched versions of dependencies in zingolib. According to [the cargo book](https://doc.rust-lang.org/cargo/reference/overriding-dependencies.html#working-with-an-unpublished-minor-version), patching applies transitively at the top level, which means we need to add [these lines](https://github.com/zingolabs/zingolib/blob/dev/Cargo.toml#L11-L14) to our `rust/Cargo.toml` in order to have the patch apply here.

I hadn't realized that when originally patching, this is an additional hassle for any crates that consume zingolib, so I'm hoping we can find an alternate solution in the near future, because keeping the downstream patched versions aligned with the zingolib patched versions sounds like absolute hell.

_Originally posted by @AloeareV in https://github.com/zingolabs/zingo-mobile/issues/86#issuecomment-1173913537_

**Comment by AloeareV** [comment]
The error message from a version mismatch is rather obtuse, with large amounts of unsatisfied trait bounds.

**Comment by juanky201271** [comment]
What do you think about this after a few months? some idea?

**Comment by juanky201271** [comment]
closing...
